### ISSUE TITLE
Overwrite Rack Layout for Racks that have Assignments

### ISSUE THREAD

**Issue by perigrin** [joyent/conch#1002]
We had a case just now where the rack layouts were populated with an outdated SKU. The devices that were put into the rack were correct so the SKU needed to be updated so that validations could proceed correctly.

To do this I had to:
1. capture the existing assignments
2. capture the existing layout
3. delete the existing assignments (with a JSON body specifying every device to be deleted)
4. update the existing layout data with the new hardware profile data
5.  restore the saved assignment data

The way that the preflight process works for the foreseeable future the assignments are less likely to change than the layout. It would be nice if we could simply update the layout without having it block on the existing assignment.

**Comment by karenetheridge** [comment]
I can change it so you can update an occupied layout iff you are changing values to things that match the device, which should fix this usecase without making the endpoint so permissive that configs can be overwritten by accident.
