### ISSUE TITLE
Device validation state doesn't return any results

### ISSUE THREAD

**Issue by dustinryerson** [joyent/conch#1019]
The `results` array in the response of the `GET  url: /device/:id/validation_state` endpoint returns an empty array.

This issue is reproducible on edge, but not on production.

Originally reported here: https://github.com/joyent/conch-ui/issues/246

**Comment by karenetheridge** [comment]
Looks to be caused by https://rollbar.com/joyent_buildops/conch/items/3871/ -- device report processing is encountering a database conflict.

**Comment by karenetheridge** [comment]
That is, this endpoint itself is functioning fine. It is returning an empty array because there are no validation results in the database to return.
