### ISSUE TITLE
Handling registered but unlocated Relays

### ISSUE THREAD

**Issue by lseppala** [joyent/conch#133]
@daleghent has been rightfully frustrated on multiple occasions by Relays that have registered (`POST /relay/:id/register`) but haven't yet reported a _located_ device don't show up in the UI.

> 3:14 PM [vendor] actually had the new PRDs connected up, but they were befuddled in that they didn't see the PRDs listed on the Relay tab of the web ui
> 3:14 PM so they thought they had a network issue 

The Relay UI calls `GET /workspace/:id/relay`. The reason registered but unreported relays aren't included in the response is because we don't have any association between a relay and a workspace until at least once device located in that workspace sends a report.

We do have data to associate a user with a relay as soon as it registers. We should expose this information in the UI. Going off the 'API tree' discussion in issue #126,  I suggest we create a new    endpoint, `/user/me/relay` to expose relays that a user has registered but not yet reported.

Open questions:

* The response for `GET /workspace/:id/relay` includes the devices each Relay has reported. Should the response should include any devices IDs that are *unlocated* (not in any workspace) but have reported through the relay be included in the response? 
* Will it confusing that the Relay will ONLY show up for the user's account who has registered registered the Relay? If integrator A registers the Relay, the Relay won't show up in integrator B's account even if they are working in the same workspace.

**Comment by sungo** [comment]
Does the new /relay endpoint (#147) help with this at all?

**Comment by lseppala** [comment]
It definitely helps! However, it requires for a global administrator (i.e. us) to be available to troubleshoot and provide reassurance when an integrator turns on a new relay. When a vendor turns on and authenticates a relay, they reasonably expect the relay to be available in the UI/CLI. They'll come to us, we'll be able to check the relay is indeed reporting, and we'll tell the vendor to continue connecting the relay to a rack. Not a big deal, but it'd be preferable if the vendor could confirm for themselves a relay is reporting.

**Comment by sungo** [comment]
What do we need to make progress on this issue or close it out?

**Comment by bdha** [comment]
I think this still requires some discussion and then scheduling.
