### ISSUE TITLE
Remove `device.validated` setting dispatch

### ISSUE THREAD

**Issue by lseppala** [joyent/conch#160]
Temporary code was added in #159 to provide backwards compatibility for Conch-Relay and Conch-Rebooter. Once these products have been updated and deployed to use the endpoint `POST /device/:id/validated` (or the orchestration system & validation system subsume this task), the temporary code marked with a TODO should be removed.

**Comment by sungo** [comment]
The code in specific is https://github.com/joyent/conch/blob/4bee1273284bc311846de8aeee4bb1c874e55c20/lib/Conch/Controller/DeviceSettings.pm#L63
