### ISSUE TITLE
Firmware update is not reflected as a status in rack view

### ISSUE THREAD

**Issue by daleghent** [joyent/conch#167]
A device that is undergoing firmware update is reflected as such in the Status section of the device's page; however the fact that it is undergoing this phase is not reflected next to the device's entry in the rack view. This may lead to an operator prematurely rebooting or turning off a server in the middle of this phase, which can lead to a inoperable server if done at the wrong moment.

**Comment by sungo** [comment]
Moved to joyent/conch-ui#5
