### ISSUE TITLE
Reduce Javascript asset size and/or optimize loading

### ISSUE THREAD

**Issue by lseppala** [joyent/conch#187]
Webpack warns that the rendered asset size is large (~600 Kb) and can impact performance (warnings disabled with this configuration line. Comment to enable: https://github.com/joyent/conch/pull/186/files#diff-57ace3d02945bd25f99fbc92d0d61ae7R2).

There may be 3rd-party dependencies that are barely used (Ramda might be a candidate) that can be removed and replaced with less code.

Alternatively, Webpack recommends code splitting, lazy loading, and caching to reduce asset size and overall performance regardless of size.

* https://webpack.js.org/guides/code-splitting/
* https://webpack.js.org/guides/lazy-loading/
* https://webpack.js.org/guides/caching/

It may be worth investigating.

Side note: this does not impact performance once loaded. As a single-page app, it's loaded when the browser first visits the site and does not change as the user navigates the site.

**Comment by sungo** [comment]
I'd like to get some metrics around the current situation. While the C programmer in me grits my teeth to 600KB of code to rend a webpage, it's really not that big. Particularly since this is a SPA.
