### ISSUE TITLE
Failed validation criteria does not present a server as "FAIL" in the device and rack views

### ISSUE THREAD

**Issue by daleghent** [joyent/conch#199]
We are seeing cases where a server will fail validation due to something, but not be marked as such in the rack view for the device, or on the device's own page as it used to be.

Currently, https://conch.joyent.us/#!/device/S309573X8224784 is one such example. Validation is failing on the system's SMBIOS name, yet it is presented as as passing system.

**Comment by sungo** [comment]
This appears to have been resolved by #202. Closing out the issue.
