### ISSUE TITLE
Want ability to create and edit racks and rack layouts

### ISSUE THREAD

**Issue by daleghent** [joyent/conch#205]
Currently, racks must be created using prepared SQL statements which create the rack database object and then populates the appropriate hardware profiles at their relevant rack elevations.

What is needed are API, Web UI, and Shell components which allow one to create racks, either from prepared structured data (such as json, yaml, or the like) or as fields in a web UI, as well as the ability to edit existing racks. An example for the latter is if a hardware profile is wrong or changes for a particular position in a given rack, then it may easily be corrected.

**Comment by sungo** [comment]
The feature request for the shell is over in joyent/conch-shell#19

**Comment by bdha** [comment]
FIxed in #267.
