### ISSUE TITLE
Remove `v1` references

### ISSUE THREAD

**Issue by lseppala** [joyent/conch#255]
We've decided a while ago that we do not want to version the API, and instead using client version checks to check for compatibility. There are many references to `v1` in the code base currently. Before cutting to the `v3` release version, let's cleans these out by renaming and removing any `v1` terminology.

Instances:
* `json-schema/v1.json`
* `as_v1_json`, `as_v1` in Perl code

**Comment by sungo** [comment]
I think all the as_v1 methods can become TO_JSON so we can leverage Mojo's autoformatting
