### ISSUE TITLE
Remove GET /problem endpoint

### ISSUE THREAD

**Issue by lseppala** [joyent/conch#259]
Remove the legacy GET /problem endpoint and associated code.

**Comment by karenetheridge** [comment]
why is this problematic?

**Comment by lseppala** [comment]
The GET /problem endpoint doesn't use the new validation results system. To get failing (and error) validations for a workspace, `GET /workspace/:id/validation-results?status=fail,error` does so.

**Comment by sungo** [comment]
Does this count as one of our lifelines? :)

**Comment by sungo** [comment]
We're currently reevaluating the code structure and its future. I'm going to close this out since it may not be applicable going forward.
