### ISSUE TITLE
validate input on `layout` and `asset_tag` POST endpoints

### ISSUE THREAD

**Issue by perigrin** [joyent/conch#303]
When a user inputs a serial number or asset tag, we need to validate its correctness (e.g. no spaces)

**Comment by karenetheridge** [comment]
What measure of validity should we use for serial numbers (which are used as the PK on the device table)?  how about `^[\w-]+$`?

**Comment by karenetheridge** [comment]
we have one device id in the database presently with a space in it (see `select concat('-',id,'-') from device where id like '% %';`) -- shall we fix it?

**Comment by sungo** [comment]
We can't be too strict here. The standards for naming things change pretty regularly. The specific issue that resulted in this ticket was "serial numbers" that had spaces in them. though

**Comment by sungo** [comment]
RE the existing device. Yes, let's craft the migration so it'll fix any existing bad devices. The concern I have is that the serial is the PK for a device.

**Comment by sungo** [comment]
As we discussed elsewhere, because the serial is the PK for a device, changing the text of it is a huge PITA. The only bad record in the production database has no FKs so we can delete it cleanly. The migration does not need to convert bad entries.
