### ISSUE TITLE
Need api endpoint for creating new hardware vendors

### ISSUE THREAD

**Issue by jemershaw** [joyent/conch#313]
There doesn't seem to be an api endpoint to create a new hardware vendor.

I believe we only need these routes:

| Method | URI |
| ------ | --- |
| GET    | /hardware_vendor |
| GET, POST | /hardware_vendor/:name |
| POST | /hardware_vendor/:name/deactivate |

**Comment by karenetheridge** [comment]
should `POST /hardware_vendor/:name/deactivate` be `DELETE /hardware_vendor/:name`, I wonder?  (@perigrin?)

**Comment by perigrin** [comment]
No because it doesn't remove the resource. That said it probably should be `PUT /hardware_vendor/:name/deactivate` since arguably it's an idempotent request at that point (and thus cache-able).

**Comment by sungo** [comment]
the current codebase uses DELETE to remove/deactivate a resource in pretty much every case. Until we're ready to redo all the other endpoints, we need to match that methodology. We do not need yet another way of doing something.

**Comment by perigrin** [comment]
@sungo has since pointed out how we currently handle this else where and yeah `DELETE /hardware_vendor/:name` is more appropriate for how we're currently doing things.

**Comment by karenetheridge** [comment]
unless I'm mistaken, I found no code whatsoever that creates hardware_vendor entries. Has this always been done manually?

**Comment by sungo** [comment]
Yes, afaik

**Comment by bdha** [comment]
Correct. There are only a handful, but there are going to be more and more. I have some I need to add now, actually.

(I expect with conch-locker these will be auto-populated, though we haven't discussed how yet.)

**Comment by karenetheridge** [comment]
This was done in https://github.com/joyent/conch/pull/393 for milestone v2.17.
