### ISSUE TITLE
Net::MAC::Vendor introduces an XS dep unnecessarily

### ISSUE THREAD

**Issue by bdha** [joyent/conch#349]
We use this module to read the OUI database from IEEE to map MAC addresses to the device vendor.

In our deployment, we want to distribute the database plaintext directly, and so do not need to uncompress the file (using `Compress:Bzip2` or `Compress::Zlib`). We want to limit new XS deps in the API -- and using the same module in conch-reporter-smartos, where XS deps are contraindicated.

It would be helpful if `Net::MAC::Vendor` only optionally required the compression modules if a local source is not specified.

**Comment by karenetheridge** [comment]
patch prepared at https://github.com/briandfoy/net-mac-vendor/pull/27.

**Comment by karenetheridge** [comment]
The patch has been applied, but not yet released to cpan.

**Comment by karenetheridge** [comment]
The patch has now been released to cpan as Net-MAC-Vendor-1.263.
