### ISSUE TITLE
Urgent fixes needed for conch-reporter-smartos support

### ISSUE THREAD

**Issue by bdha** [joyent/conch#351]
We need to get the new reporter deployed asap. A couple things I've run into so far:

```
# cat /tmp/conch-report.json | json conch | ./bin/conch -c /var/tmp/.conch.json api post /device/5T21TD2 -
{"error":true,"message":"HTTP Error: Status: 400 Bad Request\nBody: {\"error\":\"\\/temp\\/exhaust: Missing property.\\n\\/temp\\/inlet: Missing property.\"}\n"}
```
Inlet/exhaust requires a firmware upgrade, which seemingly a bunch of machines will be missing. `json-schema/input.yml` needs to be updated so these fields are not required.

```
# cat /tmp/conch-report.json | json conch | ./bin/conch -c /var/tmp/.conch.json api post /device/5T21TD2 -
{"error":true,"message":"HTTP Error: Status: 409 Conflict\nBody: {\"error\":\"Hardware product SKU 'NotProvided' does not exist\"}\n"}
```

We need to provide the `legacy_product_name` lookup function, if a device hw profile cannot be found using `product_name` or `sku`.

So far that's what I've run into.

There may be more.

**Comment by sungo** [comment]
These changes have been addressed in all the active branches.
