### ISSUE TITLE
Want to store rack SN and asset information

### ISSUE THREAD

**Issue by bdha** [joyent/conch#359]
An integrator has requested that we add rack SN and asset tag information, to reduce the amount of effort required to scan in a rack.

This requires new database fields in `datacenter_rack`, API and UI support. This is similar to fields we have in the `device` table, but for the rack itself.

**Comment by karenetheridge** [comment]
How will the incoming report data change?  How can we tell the difference between data for the rack itself, and data for devices that are in the rack?

**Comment by bdha** [comment]
This is not part of device reporting, but rack assignment. In the UI, select a rack and hit "edit assignment." The new UI bits would show up above the device SNs, and the API would update `datacenter_rack.serial_number`. `.asset_tag`, etc. (I used to know how this worked, before the move to mithril. Now @perigrin probably knows if anyone does.)

**Comment by karenetheridge** [comment]
ok @perigrin, I'm guessing that the endpoints being used here are POST /rack and POST /rack/:rack_id? We'll want to add new fields to that payload.
