### ISSUE TITLE
Add support for PDU devices

### ISSUE THREAD

**Issue by bdha** [joyent/conch#366]
Initially, we want to be able to assign PDUs to racks. 

(Later we will want full device-style reporting.)

There are potentially a few changes that need to be made here:

`datacenter_rack_layout` needs to be made aware of 0U, side-mounted PDUs. Or we can just lie about in `device_location`.

A new `hardware_product` needs to be added for each PDU type. (Preferably. We could fudge this, too, until we're ready to actually manage the PDUs from the Relay.)

**Comment by karenetheridge** [comment]
After looking at rack layouts more, I'm inclined to declare a `rack_unit_start` position of 0 for devices like these, and let as many of them tardis into the same "slot" as they want. (that is, when considering conflicts, we ignore position zero.)  then we can report on these devices on the rack just like any other, and they will be included first in the sorted list of rack layouts as well.  The bonus is there is very little support code needed for this.

Maybe we'll want to have a validation that fails if these product types ever appear in a slot position other than zero.

**Comment by sungo** [comment]
Handling this in Netbox
