### ISSUE TITLE
Add OUI lookup support to switch peers validation

### ISSUE THREAD

**Issue by bdha** [joyent/conch#368]
Something similar to https://github.com/joyent/conch-reporter-smartos/blob/master/lib/Conch/Reporter/Collect/OUI.pm so we don't have to rely on the client to submit correct data.

**Comment by karenetheridge** [comment]
Is the end goal here that we have a validation that checks that the submitted MAC address for a device matches the hardware vendor that we think it came from?

**Comment by perigrin** [comment]
Like #382 I'm closing this because the current version of conch cannot cleanly address this problem and we plan on addressing this style of problem entirely differently in future versions.
