### ISSUE TITLE
Want an API option to get device reports with a given state or time range

### ISSUE THREAD

**Issue by bdha** [joyent/conch#372]
Like "all failing reports" or "most recent failing report", not just the current "last report."

**Comment by karenetheridge** [comment]
Putting on hold as we might be stopping the storage of device reports altogether.

**Comment by perigrin** [comment]
Per current assumptions we're not stopping the storage of all reports but we are limiting the reports we store (see #619). 

I don't think we have any endpoints for serving legacy reports at all right now. I'm in favor of closing this ticket and instead creating one for a `/report/` endpoint that gives us these kinds of queries.

**Comment by sungo** [comment]
closing this in favor of #622, the larger reporting and auditing infrastructure
