### ISSUE TITLE
Want device notes

### ISSUE THREAD

**Issue by bdha** [joyent/conch#375]
We currently use spreadsheets to interact with our integrators, and this is .. sub-optimal.

Ideally we would have a device_notes table that, in addition to simply putting comments on a device, would allow us to:

* Track human actions we cannot automatically identify, like any maint work, replacing components, rebooting the system, etc. There should be a an ability to add new comment types (and we may later want to search for specific actions on a given device, group of devices, datacenter, etc.)
* Assign a comment to a user in the workspace (like Google Docs/Sheets)
* Allow user to mark a comment resolved (also like Google Docs/Sheets)

Comment types:

* Maint
* Reboot
* Ticket
* General
* ..?

Eventually when adding a comment we may want to be able to reference a specific component in the device, allowing us to track actions against that component -- or class of components when the Inventory System exists.

Some discussion of this happened [here](https://app.liquidplanner.com/space/174715/projects)./show/42442029

**Comment by sungo** [comment]
This seems a lot like reinventing a ticketing system... but in conch. I'll circle up with the relevant folks and see if we can meet this need in a proper ticketing system.
