### ISSUE TITLE
Allow for deferrable validations

### ISSUE THREAD

**Issue by bdha** [joyent/conch#379]
Example: There is a supply shortage of SSDs during a given build, so Shrimps are missing an SSD. Add a device setting to indicate that a validation may be _deferred_. Other running builds do not have a component shortage, and should continue to run the full validation suite.

An alternative to using device settings (which will be a lot of lookups) would be having Build/Project Settings, but that feature does not yet exist.

**Comment by sungo** [comment]
closed in light of https://github.com/joyent/conch/issues/619
