### ISSUE TITLE
Add triton_state field

### ISSUE THREAD

**Issue by bdha** [joyent/conch#387]
Display if Triton thinks the host is online or not.

For @bdha: This requires polling `cnapi` in production. When the system state changes in Triton, it will be reflected in Conch as well.

For @karenetheridge: It also requires adding an API similar to `triton_setup` and `triton_uuid`. We don't currently use these fields, so refactoring the API to just take a `triton` blob is fine -- or we can root things off `/triton/` prefix.

**Comment by karenetheridge** [comment]
Is this `GET /device/:device_id/triton_state`, returning the entire json blob from the (not yet created) `device.triton_state` database column?

**Comment by bdha** [comment]
It will be a string: `running`, `offline`, `unknown` and similar.

**Comment by sungo** [comment]
Is it possible for this value to be an enum and not free form?

**Comment by karenetheridge** [comment]
and where will this data appear in the report? if it's not stored, the db field will always be null.

**Comment by bdha** [comment]
Potentially, but we're pulling this from Triton's CNAPI. So we don't necessarily control the output -- though it's unlikely to change very much or at all at this point.

**Comment by bdha** [comment]
@karenetheridge It won't be in a CN report. We will need to POST it from another service that has access to CNAPI. It won't run on a CN.

**Comment by bdha** [comment]
To loop back:

We need to be able to store and retrieve the device state from Triton. This cannot come from a device report, so it will need a new API endpoint that allows us to POST to it. We have other Triton attributes we push in the same way: https://github.com/joyent/conch/blob/master/lib/Conch/Controller/Device.pm#L185-L260

**Comment by karenetheridge** [comment]
@bdha: I need some more details on this to understand what is required to be done in api, shell, and ui.

**Comment by sungo** [comment]
I concur. @jemershaw, do you?

**Comment by sungo** [comment]
Groovy. Thanks. Closing this out.
