### ISSUE TITLE
remove ability to login via user_account.name

### ISSUE THREAD

**Issue by sungo** [joyent/conch#389]

**Comment by karenetheridge** [comment]
Email only?  Presently we accept all of: user id, name and email.

I can't imagine we get many attempts to log in via user id though :)

**Comment by sungo** [comment]
automated tools should probably use the uuid. We should allow the user to change their email address and the uuid is the only immutable handle we have on them.

**Comment by karenetheridge** [comment]
we don't allow changing the email address yet, but that's easy to do via `POST /user/me/email` whenever we want it (presumably not this week though)

**Comment by sungo** [comment]
I expect we will/should so I'd like to preserve the ability to lookup by id as well as email

**Comment by karenetheridge** [comment]
code is done; PR to be submitted pending other things being merged first.

**Comment by karenetheridge** [comment]
This went into milestone 2.18 via #411 .
