### ISSUE TITLE
Add an API to list all users if you are a GLOBAL admin

### ISSUE THREAD

**Issue by bdha** [joyent/conch#396]
Current methodology to enumerate all users is to switch to all accessible workspaces. It would be useful to be able to list all users on the system from one admin context.

**Comment by karenetheridge** [comment]
What columns are useful to include in the response?

**Comment by bdha** [comment]
To start with just the `user_account` fields.

Digging through what workspaces everyone has access to would be helpful, if it doesn't require any refactoring. :)

**Comment by karenetheridge** [comment]
This was done in #429 for v2.20.
