### ISSUE TITLE
Remove `device_validate` table

### ISSUE THREAD

**Issue by bdha** [joyent/conch#397]
No longer used. Two steps to retire it:

- [x] Remove all code that references it (2.18)
- [x] Migration to drop the table (2.19)

**Comment by karenetheridge** [comment]
and presumably device_validate_criteria too?

**Comment by bdha** [comment]
Burn anything that moves or looks at ya funny.

**Comment by karenetheridge** [comment]
well that's kinda everything...

**Comment by karenetheridge** [comment]
phase 1: https://github.com/joyent/conch/pull/404

**Comment by karenetheridge** [comment]
code for both phases is done. phase 1 is merged in #404; phase 2 PR to be submitted pending v2.19 opening up.

**Comment by karenetheridge** [comment]
phase 2: #413

**Comment by karenetheridge** [comment]
This is done in #404 and #413, complete in v2.19.
