### ISSUE TITLE
Add an IPMI lookup helper

### ISSUE THREAD

**Issue by bdha** [joyent/conch#399]
This is for https://github.com/joyent/conch-shell/issues/134 `/device/:id/interface/ipmi1`. This will prevent us from returning the entire report just to throw 99.9% of it away because we want one IP.
Discussion on chat suggests having the API the arbiter of data and search is preferable to doing magical lookups in the clients.

**Comment by bdha** [comment]
Similar: https://github.com/joyent/conch/pull/367

**Comment by karenetheridge** [comment]
all device interfaces get stored into the `device_nic` table, so this means we want to select from device_nic where device_id = ? and name = 'ipmi1' -- so that implies the endpoint: `GET /device/:device_id/nic/:ipmi1/ipaddr` (or, just GET /device/:device_id/nic/:ipmi1 to get all fields from the device_nic table).

**Comment by karenetheridge** [comment]
It would be helpful to have the id of a recent device that has this data attached to it, so I don't have to spin up a production db to go hunt for one and hope that it's a representative sample.

**Comment by karenetheridge** [comment]
Which would be more useful to the shell?  `GET  /device/:id/interface/:iface_name`, or `GET /device/:id/interface/:iface_name/:field_name`?  or both?

**Comment by bdha** [comment]
```
08:18:35 gaea:~$ conch api get /device/S329229X8822031 | json latest_report.interfaces.ipmi1.ipaddr
10.100.0.24
```

**Comment by bdha** [comment]
@karenetheridge Both, I think. Less juggling if you only want a specific thing. I'd generally like to have that granular facility in the API if it's easier now.

**Comment by karenetheridge** [comment]
```
ether: 08:18:35 gaea:~$ conch api get /device/S329229X8822031 | json latest_report.interfaces.ipmi1.ipaddr
15:19
10.100.0.24
```
