### ISSUE TITLE
Remove workspace validation-states API

### ISSUE THREAD

**Issue by bdha** [joyent/conch#400]
It is very expensive, and only the UI current uses it -- in a way that we want to remove.

See: https://github.com/joyent/conch-ui/issues/15

**Comment by sungo** [comment]
This can't be processed until both the UI and the shell have removed their various functions and deployed to production.

**Comment by karenetheridge** [comment]
code is done; PR to be submitted pending blockers being removed.

**Comment by karenetheridge** [comment]
done for 2.19 in #425.
