### ISSUE TITLE
Pass in real system reports during testing

### ISSUE THREAD

**Issue by bdha** [joyent/conch#401]
We may have run into an [issue](https://joyent.topicbox.com/groups/buildops/T7bd63dd803ce29dc-M4d150b4e4add82d3999fb08f/conch-api-v2-16-2-is-in-production) where changes to the validation systems has caused switch validation to fail. We should have tests that push recent reports through validations during build.

**Comment by sungo** [comment]
I've got this on my list for the rework of the validations system. I intend that test suite to operate solely on proper device reports, some taken from production, some munged by hand to be broken in some important way.

**Comment by sungo** [comment]
We are waiting on a list of canonical device reports for testing. However, we've accomplished the basic need via the `conch-api-tester` application in joyent/conch-shell which runs reports from the last day against the staging enviornment.
