### ISSUE TITLE
Remove hardware_product.specification

### ISSUE THREAD

**Issue by sungo** [joyent/conch#418]
Back in 1d6e643ea80818a6178fac36e8783a5d0a07066d, we added a jsonb field to hardware_product called 'specification'. Apart from commands in the shell, this field is unused and will be replaced by conch-locker

**Comment by karenetheridge** [comment]
Looks like Conch::Validation::DimmMap is using this jsonb field, expecting `{"chassis": { "memory": { "dimms": [ ... ] } } }`

**Comment by sungo** [comment]
We have two systems that use the jsonb specifications, it seems. Until those are migrated into locker or some other solution, the field has to stay.
