### ISSUE TITLE
Remove device_role table and related endpoints

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch#423]
device_role was intended to hold information about the type of device (for validation purposes), but this is redundant with datacenter_rack_layout.hardware_product_id and device.hardware_product_id.

Ensure there is no production data to be lost, then drop this table and remove related endpoints in the API.   Likewise remove related shell and ui code.

Affected endpoints:

```
    GET     /device/role
    POST    /device/role
    GET     /device/role/:device_role_id
    POST    /device/role/:device_role_id
    DELETE  /device/role/:device_role_id
    POST    /device/role/:device_role_id/add_service
    POST    /device/role/:device_role_id/remove_service
    GET     /device/:device_id/role
    POST    /device/:device_id/role
    GET     /device/service
    POST    /device/service
    GET     /device/service/:device_service_id
    POST    /device/service/:device_service_id
    DELETE  /device/service/:device_service_id
```

Affected tables:

```
device_role
device_service
device_role_service
```

**Comment by sungo** [comment]
Please include the device_service table and endpoints since they exist to serve device roles

**Comment by sungo** [comment]
The shell work is complete in joyent/conch-shell#171

**Comment by karenetheridge** [comment]
Chris also confirms in https://github.com/joyent/conch-ui/issues/41 that the UI is all clear.
