### ISSUE TITLE
signal when device-slot assignments are wrong

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch#427]
The `POST /workspace/:workspace_id/rack/:rack_id/layout` and `POST /device/:device_id/location` endpoints assign device(s) to specific rack locations. Currently there is no checking, either here or anywhere else, that this `device_location` mapping makes sense with the hardware that we have referenced in the `datacenter_rack_layout` table.  There should be a validation that makes this check.

Presently, the report in `t/integration/resource/passing-device-report.json` we use for testing even fails this check -- it is trying to store a "Test Storage" device in a slot intended for a "Test Compute".

**Comment by karenetheridge** [comment]
Conch::Validation::DeviceProductName *should* do this check -- make sure that the Conch::Class/Model data that it's looking at is actually pulling from rack layouts.

**Comment by karenetheridge** [comment]
See ~thermal discussion at ~10:30PDT today for more background.

**Comment by sungo** [comment]
It does this.

https://github.com/joyent/conch/blob/master/lib/Conch/Validation/DeviceProductName.pm#L24

Verifies the hardware_name property (which comes from https://github.com/joyent/conch/blob/master/lib/Conch/Validation.pm#L277 ) against the name in the report.

**Comment by karenetheridge** [comment]
device -> slot assignments are checked, but there is no sanity checking when creating the initial rack layouts that the assigned hardware will fit.
