### ISSUE TITLE
migrate endpoints in conch_stats repo into conch

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch#434]
There are old queries in conch_stats that no longer work with the new schema. Pull them into the main API as unauthed endpoints.

**Comment by karenetheridge** [comment]
The endpoints are all unauthenticated. They are:

* `GET /workspace` - get arrayref of all rows from workspace table.  This differs from our existing `GET /workspace` endpoint (which includes permission information, and is limited to workspaces that the currently-authed user can reach).

* `GET /workspace/:workspace/rack-totals` - get arrayref of hashes containing keys: role_name, count -- a count of the number of role names found in that workspace.

* `GET /workspace/:workspace/device-totals`

**Comment by sungo** [comment]
Please verify with the server logs but I think we don't need to port the `/workspace` endpoint, particularly since it bypasses our usuall permissions.

**Comment by karenetheridge** [comment]
Looks like the only one in use is device-totals.
