### ISSUE TITLE
use read only credentials for read only db connection

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch#440]
we're not using the ro db connection yet in the conch api, but will soon.  Ansible has the ro creds so we should use that login, à la: `pg => 'postgresql://conch_read_only:{{conch_readonly_db_password}}@{{database_host}}/conch'`

**Comment by sungo** [comment]
the conch-stats api was, in theory, using the ro db connection

**Comment by karenetheridge** [comment]
Yup, that's how I realized those creds existed :)
