### ISSUE TITLE
Add an 'admin' bit to the users, replacing the 'global admin' hack

### ISSUE THREAD

**Issue by sungo** [joyent/conch#443]
We currently use the notion of having admin on the GLOBAL workspace to mean "admin of all of conch". Since a lot of conch has nothing to do with workspaces, let's replace that with an admin bit on the user account.

**Comment by karenetheridge** [comment]
do we care about updating https://github.com/joyent/rfd/blob/master/rfd/0134/README.md ?

**Comment by karenetheridge** [comment]
I will also add an option to the 'create user' endpoint to set the admin flag, as otherwise we won't have any mechanism for creating admin users.
