### ISSUE TITLE
device.health is freeform; should be an enum

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch#447]
looks like the only possible values are PASS, FAIL, UNKNOWN and ERROR.

**Comment by sungo** [comment]
Paging @jemershaw 

I'm pretty sure this value is getting set from livesys. My gut says to leave it freeform so that we don't put restrictions on livesys. What are your thoughts?

**Comment by jemershaw** [comment]
We are using freeform right now so leaving it would be best -- I can work on the backend changes to support this in livesys and the reporter.

**Comment by karenetheridge** [comment]
device.health is set internally, as a byproduct of running validations, so we can make this change now.
