### ISSUE TITLE
Adding an unique short name to define a room

### ISSUE THREAD

**Issue by jemershaw** [joyent/conch#454]
Now that we are deploying datacenters that support custom nictags to handle the layer 3 aspect of triton/manta, we need to add another column to datacenter_rack, this would be a text field that would uniquely identify a physical location using < 6 characters.

I am thinking since we already have a vendor_name and alias this could be named code ,name, short_name, or short. I'm sure we might be able to use alias but we'd have to see if anyone else is using that field for something.

**Comment by karenetheridge** [comment]
datacenter_rack already has a name column. I think this is what you get returned in the response from `conch ws <workspace> racks`?

**Comment by jemershaw** [comment]
Sorry I was looking the schema which was called vendor_name.

**Comment by jemershaw** [comment]
Well I'm an idiot -- I mean't datacenter_room.

**Comment by perigrin** [comment]
I think we're going to be using `alias` for this so closing.
