### ISSUE TITLE
New endpoint for accepting time series data

### ISSUE THREAD

**Issue by sungo** [joyent/conch#458]
We need to be able to accept time series data from the relays and pivot it into some place useful. We initially need to support circonus, but should probably make it pluggable in case prometheus or something else comes into play.

The endpoint should accept an authenticated PUT or POST. No GET or DELETE is needed since we are just pushing data upstream.

@perigrin what are your thoughts on url structure?

**Comment by karenetheridge** [comment]
(as discussed) one metric that would qualify here is temperature -- getting this out of device reports will help us de-dupe them.

**Comment by karenetheridge** [comment]
Proposal:

    POST /device/:device_id/environment

json payload (inflated perl-style for readability):

    {
        temp => {
            cpu0 => 20,
            cpu1 => 20,
            inlet => 20,
            exhaust => 20,
        },
        voltage => {
            psu0 => 1.2,
            psu1 => 3.2,
        },
    }

Upon receipt of this data, we will:

* store it into `device_environment` (at least for now). all the above fields already have columns in this table, although we have never been processing/storing voltage data so far enven though some reports do contain this data.
* invoke an appropriate validation plan to check this data.  (what to do if validations fail is still undefined.)
* send it off to circonus (if the endpoint is ready), or log to a file for later import to circonus.

**Comment by karenetheridge** [comment]
Now is a good time to provide feedback as to the format of the data coming into this endpoint, as well as the format of the data that will be logged as json (to be fed into circonus later on). It would be best if we mangle the data as little as possible between each layer.

**Comment by sungo** [comment]
Superseded by #624
