### ISSUE TITLE
Remove old device reports

### ISSUE THREAD

**Issue by sungo** [joyent/conch#461]
We have millions upon millions of old device reports. We need to figure out which ones to keep and which to burn and how to do so.

**Comment by karenetheridge** [comment]
taking an initial stab, using pseudocode:

```
foreach device,
    consider all device reports, in reverse chronological order:
        if report has no associated validation_state record, see if there's another `device_report` row with identical json. if so, nuke it.
        if report passed, and the next report (the one we looked at in the previous loop iteration) also passed, then delete the `device_report` row,, its associated `validation_state`,  all `validation_result` rows etc.
        if report failed, see if its associated `validation_result` records all match the records for the report we looked at in the previous iteration. if so, delete the `device_report` row,, its associated `validation_state`,  all `validation_result` rows etc.

This is going to be *slow*.. we'll be stepping through all device_report records in the db and also doing some jsonb equality queries in the db.

**Comment by sungo** [comment]
We probably can't use JSON equality as a decision point. Device reports contain temperature of the server and is often different between reports.

**Comment by karenetheridge** [comment]
Do we care about preserving historical temperatures? If not, we can write a comparison routine that ignores that field.

**Comment by sungo** [comment]
Paging @jemershaw

**Comment by daleghent** [comment]
Ephemeral values for things such as system and disk temperatures (and perhaps in the future fan speeds or voltages... stuff like that) are ever-changing and are comparatively rarely a reason for us to flag a system for inspection in integration or pre-production. I think we can ignore those values. In production, a more appropriate venue for storing and alerting on these would be the regular production monitoring system (ie, Circonus and its agents) 

In this case, we can identify these elements of a report and ignore them for comparison reasons. They really are things that are useful in the moment they are generated and not much beyond that for our purposes.

**Comment by sungo** [comment]
@daleghent we have #458 as well joyent/conch-relay#152 open for extracting that data from device reports and pivoting into a pluggable TSDB system.

**Comment by daleghent** [comment]
+1 on offloading such data to a TSDB for cold storage. We only need the temps for validation purposes upon receipt of the report. Ignore them for the purposes of de-duping and go shrink that table :)

**Comment by karenetheridge** [comment]
When comparing report json blobs for equivalence, what fields should I be ignoring? so far I just have (using perlish format for referencing fields):

* `{temp}`
* `{device}{*}{temp}`

Is there anything else?

**Comment by karenetheridge** [comment]
> taking an initial stab, using pseudocode:

That turned out to be entirely unhelpful, as I can't effectively compare validation states against each other.  I settled for a pure comparison of device report json blobs, after filtering out the time-series data like temperature, psu voltage and fan speed, without regard to pass/fail status.

In pseudocode, this now amounts to:

    foreach device, oldest device first:
        foreach report, newest first:
            if an *earlier* report than this one can be found, with "same" json, delete it.

Thus we will keep only the *earliest* unique report for each device.  Associated orphaned validation_state, validation_state_member and validation_result rows will also get deleted.

**Comment by sungo** [comment]
The original intent of this issue is still valid but the list of what we delete is altered by https://github.com/joyent/conch/issues/619. I think we can track this listed requirement over here "Additionally we'll need to write a script that purges the data base of all reports not matching the above criteria."

**Comment by karenetheridge** [comment]
With the deployment of 2.24 and the running of `bin/conch thin_device_reports` in production, this at last can be closed.
