### ISSUE TITLE
Document endpoints, including their JSON Schemas

### ISSUE THREAD

**Issue by sungo** [joyent/conch#471]
I'd like a standalone document that lists the API endpoints, their parameters, the JSON schema expected for their input, and the JSON schema that they emit.

While much better than a few months ago, this currently requires spelunking through the code a bit.

Bonus points for figuring out how to autogenerate the document

**Comment by sungo** [comment]
Modifying my requirements a bit. Now that we have generated docs, via #752, and a github pages site, I'd like these docs integrated into the Route modules, documenting the end points, their parameters, and the json schemas used for both input and response. Where possible, these should generate proper links so that the github pages can be clicked through. I recognize that links to schema bits will probably have to link out directly the repo and that those links will be fragile. 

I don't need large prose descriptions of the endpoints and how they tie together. Right now, I need simple descriptions of the endpoint and the ins/outs. For instance, most of our endpoints are CRUD. I don't need a description for the GET methods as "get a single $foo" and DELETE as "delete a single $foo". That should be pretty clear already from the URL structure and response data.

**Comment by karenetheridge** [comment]
Agreed - for v2, we need full documentation of our endpoints. Whether we move that documentation somewhere else in v3, or generate it from code etc is a v3 concern and is orthogonal to this ticket (but the work done here will help influence the direction taken in v3).
