### ISSUE TITLE
Change the device table so it uses a UUID as its PK

### ISSUE THREAD

**Issue by sungo** [joyent/conch#474]
Currently, the primary key on a device is its `id`. Unlike everywhere else in the database, `id` here is a text field containing the serial number of a device. This leads to the situation we ran into with #303 where we can't fix the serial number of a device without doing massive database surgery.

We need to transition things such that the PK on the device is a UUID like the rest of the database.

**Comment by sungo** [comment]
Marked as "low priority". This needs to get done eventually but we have other more important fish to fry at the moment.

**Comment by karenetheridge** [comment]
We have the same issue with relays -- using its serial number as an id rather than generating a UUID - so we might want to make the same fix there as well.

**Comment by karenetheridge** [comment]
Many endpoints send old-device_ids (serial numbers) in their input payloads; many of these can be easily transitioned to using device uuids, but some (e.g. rack assignment) are not so straightforward, as they do not require the device to actually exist yet (therefore we would create the device row and generate its uuid after receiving the serial number as input).  Some revision of the api spec is needed to decide which endpoints should change and how.

**Comment by karenetheridge** [comment]
I will presume for now that device reports will be submitted under their serial number, we will respond with the assigned device id, and all other device-related queries will use the uuid rather than the serial.  If some need to be adjusted to also accept serial, we can address that later and is not considered a blocker.

**Comment by karenetheridge** [comment]
see #790 - some cleanup of the device and device_report endpoints are needed to remove some ambiguity.
