### ISSUE TITLE
JWT should use `set_iat` and a uniform `expires` time

### ISSUE THREAD

**Issue by perigrin** [joyent/conch#476]
We could be leaking account privileges because we assign different expiration times based on account level. We should instead set a single uniform expiration time (to trigger refreshing) and use the issued_at timestamp to validate old tokens.

**Comment by karenetheridge** [comment]
note this will require changes in buildops-infra as well as the default expiration times are configured in there.

**Comment by perigrin** [comment]
Actually what I had in my head was just invert the current logic. Instead of setting `expires` to `time + $config{time}` when we do the _check_ we check if the issued_at is before  `time - $config{time}` ... 

We'd only need to change `buildops-infra` if we wanted to add an additional expiration time so that the shell would know when a safe period to refresh within was.

-Chris

**Comment by sungo** [comment]
currently, the shell does not store the issue time of the JWT. It only looks at the expiry time inside the claims section. It uses that value to decide when to do a refresh, defaulting to a day before expiry. (This replaced previous logic where the token was refreshed before every command.)

If the intention is to change this logic without requiring a change in the shell, the expiry time still needs to be passed in the claims section of the JWT.

**Comment by perigrin** [comment]
I think we still have an issue here, but having dug deeper into the way our auth system works, this is complaining about the song the band is playing while trying to get to the lifeboats. I'm closing this with the idea that we'll cover it in a bigger refactor later.
