### ISSUE TITLE
API Token System

### ISSUE THREAD

**Issue by sungo** [joyent/conch#478]
I'd like a system by which a user can generate API tokens that live forever for use in automated applications. Users should be able to generate and revoke tokens at will ~~and assign privileges to them.~~

* `token`
  * unique identifier
  * name (unique for the user)
  * created
  * last_used
  * deactivated
* join between `user` and `token`
* ~~join between `workspace` and `token`~~
  * ~~token id~~
  * ~~workspace id~~
  * ~~role (same as user join: 'ro', 'rw', 'admin')~~

* Permissions are inherited just like those of a user
~~* A user can only grant permissions at or below the level they have in a given workspace~~
* The token should be presented ~~as an auth header of some sort.~~ _in the `Authorization` header_ 
* Logs should contain both the token name and user name associated with it for every query made

* URLs
  * `GET /user/me/tokens` - get a list of active tokens. Query parameter should provide ability to get revoked tokens as well
  * `GET /user/me/token/:id` - Get information about the specified token, including the workspaces it has access to.
  * `POST /user/me/token` - Create a token. Can take a list of workspaces and roles
  * `POST /user/me/token/:id` - Update a token. Can take a list of workspaces and roles
  * `DELETE /user/me/token/:id` - Deactivate a token

This probably needs further refinement. @perigrin, I'd like a lot of your thoughts here.

**Comment by sungo** [comment]
I'm looking at some shell security issues (joyent/conch-shell#280) and life would be made considerably easier there if the API had a token system.

I'd like the token to contain enough data that the user does not need to know a user name. For instance, they might run `TOKEN=$token bin/conch`. Not only would this prevent leakage of the user name / email address (minor issue), it would allow the edge to continue working if the user changes their login information.

**Comment by karenetheridge** [comment]
I would propose `s/deactivated/expired/` in the `token` table, to allow for tokens that have been deactivated already (timestamp is in the past) and tokens that will expire in the future (timestamp is in the future). then we just search for tokens with expired=null or expired >= now().

Can tokens just be plain old uuids, or do we need to use some sort of crypto to carry a payload?

**Comment by sungo** [comment]
My original thought was a JWT because it could be signed (super stretch goal for all parties) and carry a more payload usable by the client. Not entirely sure what we'd put in there yet but it'd offer future expansion. But if that doesn't sound interesting to anyone, then a UUID or some other string would suffice.

**Comment by karenetheridge** [comment]
> join between `user` and `token`

If tokens are for the exclusive use of one user, we can just put a `user_id` column in the `token` table. Are there situations where another user might be given or have access to a token created by someone else?

**Comment by sungo** [comment]
No. Tokens should only be used by a single user and we should have some method to prevent their use by other users.

**Comment by sungo** [comment]
Talking in chat, it might be interesting if the payload encoded the api server's url. In the shell, it'd let me use the token as the source of truth about what api server we're talking to. I could extract that from the token and the user wouldn't need to provide it.

Not required or anything like that but it's an interesting (to me) thought.

**Comment by perigrin** [comment]
Looking at this there is no strong reason I can think of *not* to have it be a JWT. We already support JWTs extensively in the application elsewhere so there's no additional cognitive load  for users on why this token is a JWT and that one is just a UUID.

Re-iterating from chat: JWT would also allow us to encode some of the features the client could use like the `aud` (audience) claim to limit the client to a specific API instance and/or auto-detect which API instance we care about (rather than store that information separately). I'd probably also include the creating user's ID in the `sub` claim so we could log it quickly without having to do a trip to the DB.

**Comment by sungo** [comment]
I don't know what you mean by "the creating user". To my way of thinking, the user themselves should be the only creating tokens for their account. We already have the user's UUID in the JWT.

**Comment by sungo** [comment]
For ease of first-implementation, I suggest we use UUIDs as the token, with the control and user flows as I laid out in the original post.

I suggest we return that uuid in the same authorization header that we use now for jwt, which would allow you to do an `is_uuid` check on the value to determine if you should check the token system or not.

**Comment by perigrin** [comment]
I entirely missed that we invented our own claim rather than re-using the (admittedly less straight forward) standard one. So yes the `sub` claim bit is currently `uid` in our tokens.

**Comment by karenetheridge** [comment]
The `user_session_token` table already contains most of the functionality we need: https://github.com/joyent/conch/blob/master/lib/Conch/DB/ResultSet/UserSessionToken.pm#L67-L87

I would suggest just adding a id (uuid type) column to that table, so as to allow for joins to workspaces etc, and add the endpoints to provide CRUD operations on that table.

**Comment by karenetheridge** [comment]
>  The token should be presented as an auth header of some sort.

What header? For what endpoints?  If the user has multiple tokens, which do we include in the response?

Since the user token has its own association with workspaces and roles, do we use this as an orthogonal permissions system for accessing workspaces? Should we consult this table whenever the user requests access to a workspace? Or just when they present this token? Does that mean we should expect to see this token showing up in request headers? (and where? we already authenticate using a JWT. should we upgrade the user's workspace permissions for the duration of the session in which they authenticate with *this* token, as opposed to *that* one which had lesser permissions?)

I can implement the crud endpoints specified here, but for additional functionality/features, I need more specs.

**Comment by perigrin** [comment]
These tokens would be used in place of the current JWT tokens, for clients that don't want to use the current login + user session system (e.g. the shell, relays, and reporters). The token will be presented by the client in the `Authorization` header with a `Bearer` scheme (exactly as the JWT is currently presented by the shell) for all endpoints that require authentication. The API will then validate this token upon every request, as it currently should be doing for JWT, to asses the authentication and authorization of the client for that request.

I agree that the current `user_session_token` (and the JWT system) looks very similar to our needs here, and Sungo has said in chat he doesn't care what the token looks like as long as he has an opaque string he can use to simplify authentication in the shell. So I believe that the current JWT system could easily be expanded to satisfy the needs of this ticket as long as the following differences are understood:

1) API tokens have no expiration time, user session tokens are limited to 1 day / 30 days (depending).
2) API tokens are managed via the API above, user session tokens *are not*.
3) API tokens generated by a user may have a different (more restricted) set of permissions than those of the user _themselves_. 

So in addition to the rules outlined in the ticket above we also would need to have:

* When a user is removed from the system all associated tokens for that user are *also* removed
* If a user's permissions are changed, we need to scan the associated tokens to remove any permissions the user may no longer have.

**Comment by karenetheridge** [comment]
> So I believe that the current JWT system could easily be expanded to satisfy the needs of this ticket

I've never suggested doing that.

**Comment by sungo** [comment]
@perigrin is correct in that I want a non-expiring opaque thing to pass up in the Authorization header.  

Where @perigrin and I disagree regards changing the permissions system when it comes to tokens. I strongly suggest that we start by making tokens equivalent to a regular login. Logging in via the web browser and logging in with a token should provide the same levels of access. I know that I suggested otherwise in the originating comment and I'll go strike that out. 

Down the road, we may want to be fancy and introduce authorization scopes (github and netbox are good examples). But for the purposes of this ticket, no new permissions or scopes are required.

**Comment by sungo** [comment]
Superseded by #726
