### ISSUE TITLE
Removing accounts from workspace

### ISSUE THREAD

**Issue by jemershaw** [joyent/conch#487]
When removing accounts from conch using `conch admin user $email rm --force` it
seems as though the workspace settings still exists which makes it confusing to
see who still has access to the workspace.

Should we remove the user_workspace_role equal to the users UUID?

**Comment by karenetheridge** [comment]
Can you show me an example of what you mean?

**Comment by karenetheridge** [comment]
> Should we remove the user_workspace_role equal to the users UUID?

That is - when deactivating a user, should we remove all permissions associated with the user, so if/when we reactivate them, they have to be re-added to all workspaces again, or should they get their original permissions back?  At the moment it's the latter.

**Comment by sungo** [comment]
We should remove all permissions associated with a user when they are deactivated.

**Comment by karenetheridge** [comment]
> The GET /workspace/:id/user endpoint only lists active users

This is true only in staging (v2.20, where we reworked all the workspace permissions to be inherited). In prod (v2.19), deactivated users are still listed.

So, I think this is a case of "already fixed in v2.20". Closing!
