### ISSUE TITLE
need monitoring and alerts on conch-api

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch#503]
nagios or something like it should be alerting us to problems as they happen on production. Right now, we could have a broken endpoint (e.g. stacktraces, or incompatible json schema changes to reports) and we won't know until a human notices and reports it. It would be bad if we started rejecting most device reports and didn't notice.

e.g.:

- tail the log and watch for a high frequency of 4xx or 5xx errors
- api becomes unavailable entirely

**Comment by sungo** [comment]
For joyent deployments, we need to use circonous for this. We also have an ELK stack available to us. Further, let's move this over to joyent/buildops-infra since it is not related to the general codebase.

**Comment by satishvarmadandu** [comment]
Is there any way to specify alerts frequency to few mins rather than hourly. The minimum frequently we are seeing through UI is 1 hr and that's a blocker for us.

**Comment by karenetheridge** [comment]
@satishvarmadan this issue is describing new monitoring that doesn't exist yet. Could you open a new issue on the 'conch-ui' repository describing your issue?
