### ISSUE TITLE
Adding netbox API functionality to conch API

### ISSUE THREAD

**Issue by bdelano** [joyent/conch#506]
I now have a netbox branch which needs to be reviewed, so we can determine the best place for the code.  At the moment it is using the standard routes and controller, but wasn't 100% sure at where this needed to be.

**Comment by karenetheridge** [comment]
If you create a pull request, we can see the branch directly and offer comments at specific lines of code.

**Comment by bdelano** [comment]
I'm closing this as from my discussions with sungo it really isn't possible to add this integration as making requests against a device that doesn't already exist will break everything... Will try and get the conch-reporter-smartos working, so we can back fill all the legacy devices

**Comment by karenetheridge** [comment]
> so we can back fill all the legacy devices

..and we can certainly write endpoint(s) to help with that backfilling of data.
