### ISSUE TITLE
collapse /hardware_product and /db/hardware_product endpoints together

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch#517]
Current endpoints:

```
    GET     /hardware_product
    GET     /db/hardware_product
    GET     /hardware_product/:hardware_product_id
    GET     /db/hardware_product/:hardware_product_id
    POST    /db/hardware_product
    POST    /db/hardware_product/:hardware_product_id
    DELETE  /db/hardware_product/:hardware_product_id

```

1. all endpoints will move to `/hardware_product/*`
2. the first two pairs are essentially duplicates of each other, and the `/hardware_product` endpoints return more data (including profile and zpool data in the responses), so let's keep those.

Now is also a good time to fix anything else we want about the responses.  e.g. in the responses for `GET /hardware_product/*`, `hardware_vendor_id` is returned as `vendor` - let's undo that and use the proper column name.

**Comment by karenetheridge** [comment]
This is a prerequisite for #511.

**Comment by karenetheridge** [comment]
I have encountered the following conflicts between the endpoint implementations, and made the following decisions:

* in /db/ endpoints (both GET and POST), 'vendor' is the vendor id.
    in non-db endpoints, 'vendor' is hardware_product_vendor.name.
   
**decison:**  in inputs, I will take either 'vendor' or 'hardware_vendor_id'. in outputs, I will return 'hardware_vendor_id' only.

* old GET /hardware_product didn't fetch anything without an associated profile vendor.

**decision:** I will remove this behaviour. all products will be returned.

* old GET /hardware_product included the profile in the results; the GET /db/hardware_product did not include the profile.

**decision:** I will include the profile in the results.

**Comment by perigrin** [comment]
These resolutions seem fine to me.

**Comment by karenetheridge** [comment]
this is a test
