### ISSUE TITLE
Ability to operate on workspaces by string name

### ISSUE THREAD

**Issue by sungo** [joyent/conch#540]
Workspaces have a unique string name but the API currently only supports accessing them by UUID. For the shell, if a user wants to access data about a specific workspace, I have to pull the list of all workspaces and dig out the UUID. I'd rather be able to provide the string name instead of the UUID in workspace operations.

**Comment by karenetheridge** [comment]
So basically all the endpoints that take `/:workspace:id` should also handle the name in its place? ok, that's easy to switch on by checking `is_uuid()` on the incoming string.

**Comment by sungo** [comment]
Elsewhere, are we still doing that = stuff? `GET /whatever/name=wat/` ? Do we want to keep doing that? I kinda hate that syntax but maybe that's just me :)

**Comment by karenetheridge** [comment]
I kind of hate the `name=foo` syntax too. It is less ambiguous though than having to infer the type. @perigrin what do you think?

**Comment by sungo** [comment]
For the most part, we have one unique string identifier per thing so there's little ambiguity. Except... *except!* devices that have a million unique string identifiers. So, in the cases that are not devices, we could get away with `:id` being a UUID or string and know what we're talking about. Except...

**Comment by sungo** [comment]
Sorry, it's hardware products that a ton of unique identifiers, not devices

**Comment by karenetheridge** [comment]
Yeah, we can't infer the type for devices (or relays), where we don't use uuids. We're fixing that "soon" though, with #474 :)

**Comment by perigrin** [comment]
I really hate `/foo=bar/` and would prefer just using query parameters.
