### ISSUE TITLE
Expose device_disk

### ISSUE THREAD

**Issue by sungo** [joyent/conch#543]
We collect and store a lot of data about the drives in a system, stored in `device_disk`. I don't see a way to extract that data via the API. I suggest including it in a `DetailedDevice`, just like we do with `device_nic`

**Comment by karenetheridge** [comment]
FWIW, the disk information will be there in the 'latest_report' part of the hash, but we can return it explicitly as well.

**Comment by sungo** [comment]
We have explicit tables for this so we should use that. The format of the devices reports has changed enough over time that I don't use it for anything in the shell other than to dump it out at the request of the operator.
