### ISSUE TITLE
Add device_memory information to DetailedDevice

### ISSUE THREAD

**Issue by sungo** [joyent/conch#552]
We are extracting information about the memory in a device from the device report into the device_memory table. Near as I can tell, this data is inaccessible from the API. I'd like to see it added to the DetailedDevice response so it is available via `GET /device/:serial`

**Comment by sungo** [comment]
See also #551

**Comment by karenetheridge** [comment]
> We are extracting information about the memory in a device from the device report into the device_memory table

We're not, actually. At least, I see no code that inserts into that table, and that table is empty in the backup from production from ~September that I'm using.  We'll need some specifications around that section of the report so we know how to fetch that data; I'll punt this over to #551.

**Comment by sungo** [comment]
Looking through livesys, specifically https://github.com/joyent/conch-livesys/blob/master/Conch-Reporter/lib/Conch/Reporter/Collect/Memory.pm , I don't think we're even collecting all the data we need to fill the table in the database.

**Comment by karenetheridge** [comment]
question for reporter folks: do we care about what slot a dimm is in? can/should that just be inferred from the array index?

**Comment by sungo** [comment]
We care about it for reporting purposes. It's important to know exactly which dimm is busted so integrators don't waste time guessing

**Comment by sungo** [comment]
Obsoleted by #650
