### ISSUE TITLE
rewrite validations to only act on the database, not device reports

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch#555]
Presently the validation modules act on a combination of data already written to the database (device, hardware_product, hardware_product_profile, datacenter_rack_layout among others), *and* the raw device report. Most validations cannot run without some out-of-band data being passed in, even if the data it uses has already been written to the database somewhere.

This is horrid and makes it difficult to restructure the device report workflow, not to mention restructure how reports are laid out.

As also required in #551, all useful data should be extracted from device reports and transferred to the database, then validations should run solely against the database.

**Comment by karenetheridge** [comment]
We need to revisit this and determine if we really want to go this way -- as there are various downstream implications -- e.g. do we *always* want to copy all data from device reports into other database tables, and then only validate against those. e.g. take a look at the `device_spec` table.

**Comment by sungo** [comment]
or we go the other extreme. drop all the tables, use *just* the (deduped) device report json. The API would need to contend with the shifting formats when building responses, of course.

**Comment by perigrin** [comment]
So it currently looks like we're going to do what @sungo suggested on Dec 13, 2018 and go the other extreme. We are will move to just using the device report JSON for validation.
