### ISSUE TITLE
Check to make sure `dimms` and `cpus` are arrays and not objects.

### ISSUE THREAD

**Issue by perigrin** [joyent/conch#559]
@daleghent  pointed out on chat that we're occasionally getting single object values for dimms and cpus when they should be lists.

We currently have nothing that even checks that we're getting a dimms and cpus key in the Device Report. We probably should.

**Comment by karenetheridge** [comment]
When we parse the device report in lib/Conch/Controller/DeviceReport.pm, nothing extracts that data and moves it to the device_memory table.

This (with the schema update) will need to be fixed before #551.
