### ISSUE TITLE
POST /device/:id/* endpoints not checking for user permissions

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch#561]
Presently, a user can make changes to any device even if they lack any 'rw' permissions for the workspace(s) the device resides in.

(This is easy to fix in the `find_device` method in the dispatch chain by doing a request method -> required permission lookup, just as we do in `find_workspace.`)

We'll need to be careful that users have the right permissions - we know that relays have rw perms because they mutate device settings (the one place we *are* doing permission checks right now), but other users may have problems.

**Comment by sungo** [comment]
AFAIK, the relays are all using GLOBAL-admin class users.

**Comment by karenetheridge** [comment]
They can't be, because https://github.com/joyent/conch/issues/558 exists.

**Comment by sungo** [comment]
Jeff was trying to stop using admin class users for the relays but can't. Take a look in the database at all the '+' style email addresses
