### ISSUE TITLE
Want validation for hdd block size

### ISSUE THREAD

**Issue by daleghent** [joyent/conch#574]
On request of CPG, the new Ceres Type-2 and NCP Type-1 servers are being shipped with their hard drive block sizes set to 4k native rather than the default 512e (emulated). It has been requested that we verify the block sizes on these servers that they are indeed 4kn and raise a validation fail if any are found not to be. Corresponding issue for adding block size to the reporter is joyent/conch-livesys#112

**Comment by sungo** [comment]
Once you've nailed down what the report data will look like, please follow up in this ticket as a specification so the validation can be developed against that data.

**Comment by perigrin** [comment]
@daleghent you closed https://github.com/joyent/conch-livesys/issues/112 in December but never updated this ticket with the new data format so a validation could be developed. Can you provide an update?

**Comment by karenetheridge** [comment]
For now I will just write a new HddSize validation that looks in a new section of `hardware_product.specification` and we can tweak that if my initial guesses aren't correct.  Any hardware products that don't have anything at all in that section of its specification field will skip past this validation - it will only pass/fail if there is *something* there to indicate that a drive size check should be done.

Actual data can be submitted using the existing endpoints for updating hardware products -- see https://joyent.github.io/conch/modules/Conch::Route::HardwareProduct

**Comment by sungo** [comment]
After talking to @daleghent, here's what we're thinking.

The existing device report contains data that looks like this, roughly
```
{
  "disks": {
    "$serial_number": {
      "block_sz": 4096,
      "model": "M123456",
    },
  },
}
```

We should use the `specification` field on the hardware product profile to pass in the expected data. That json should look like
```
{
  "disks": {
    "_default": 512,
    "M123456": 4096,
    "M123467": 8192,
  },
}
```

if the device's hardware profile specification lacks the `disks` section, the validation will be skipped.

The validation should iterate through each drive in the device report and compare `block_sz` to the value in the specification based on model number. If they do not match, the validation should fail.

The `block_sz` field is being normalized at the edge to bytes so we don't need to worry about variations.

**Comment by karenetheridge** [comment]
Other than `_default`, that's exactly what I implemented. PR coming shortly.
