### ISSUE TITLE
`/logout` and `/reset_password` should require authentication 

### ISSUE THREAD

**Issue by perigrin** [joyent/conch#594]
Currently it looks like the `/logout` and `/reset_password` methods don't require authentication to trigger, but I'm not sure that makes any sense since we'd need to have a valid user (and session) for them to work no?

They should probably be placed along side `/refresh_token` and dispatch off of `$authenticated`.

**Comment by sungo** [comment]
I recall the `reset_password` permission being intentional. Something about not being able to reset your own password if you can't log in. It does create some opportunities for "hilarity", of course

**Comment by karenetheridge** [comment]
`/logout` could be an authenticated endpoint, but it doesn't really change the outcome any -- as the logout implementation is simply 'delete the JWT cookie'. Is it helpful for the caller to know ahead of time if he already was logged in, before logging out (i.e. logout should fail, vs returning a 204, if not already logged in)?

**Comment by sungo** [comment]
I'm going to punt this off to the SSO app, #512. The current situation doesn't hurt anything, from what I can see, and we can reevaluate the feature as we're reimplementing auth over in SSO.
