### ISSUE TITLE
remove /workspace endpoints that mutate data

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch#595]
as per https://github.com/joyent/conch-ui/issues/70, `/workspace` endpoints should be read-only.  Relevant endpoints should be removed after the shell and ui stop using them.

**Comment by karenetheridge** [comment]
Looks like the only relevant endpoint is `POST    /workspace/:workspace_id_or_name/rack/:rack_id/layout`

**Comment by karenetheridge** [comment]
as on chat: so instead of (the current) `POST /workspace/:workspace_id_or_name/rack/:rack_id/layout,` maybe that should be `POST /rack/:rack_id/device_location`
with the same payload as before: a json hash of { device_id => rack_unit, ... }
and `POST /device/:device_id/location` can remain unchanged (requiring the device to already exist).

**Comment by perigrin** [comment]
Per @karenetheridge on joyent/conch-shell#200:

> Note that the equivalent non-workspace command to POST /workspace/:workspace_id_or_name/rack/:rack_id/layout is POST /device/:device_id/location, but the latter requires the device to be already created, whereas the former will create the device for you as needed (using the hardware_product_id from the layout).  

The UI apparently uses this feature. When a rack is created, the devices aren't created yet instead a Layout is created stating which hardware profiles are in which slots on the device. Then later as a side effect of populating the Layout with Serial Numbers the devices are created. 

So I'm thinking we should have a new endpoint entirely, as we're currently discussing in chat.

**Comment by karenetheridge** [comment]
This endpoint can go away as soon as nothing is dependent on it anymore.
