### ISSUE TITLE
Phases

### ISSUE THREAD

**Issue by perigrin** [joyent/conch#621]
Currently Conch only validates devices during "preflight" and has no concept of 
Phases. We are planning on adding in-flight reports from production machines
and the reality of pre-flight is that it has two distinct phases. So we will
need to introduce the concept of phases to conch reports. Specifically for 
our current preflight uses we will need:

1. `Integration` 
2. `Installation`
3. `Production`

Integration is the assembly of the racks at the integration facility. 
Installation is the delivery and installation of the racks at the DC, and
Production is the final sign-off and accepting user requests.

Eventually we will need to divide Production into `Production` and 
`Diagnostic/Repair` to allow for in-production downtime for operations
(hardware swaps, firmware updates etc). We may also at some point add 
post-production phases like `RMA`, `End-of-Life` and `Decommissioned`.

Phases will be set via a new endpoint `/device/:id/phase` (TBD) similar 
to how device locations are set. Until we start tracking in-production 
and _especially_ `Diagnostic/Repair` states we can assume that a given 
report is for `Integration` unless told otherwise.

With the addition of phases we will need to update the report retention policy 
to retain the first and last reports for a given phase.

**Comment by sungo** [comment]
I suggest the initial phase list consist of "integration", "production", and "decommissioned"

**Comment by perigrin** [comment]
Looking at our needs over for 2019H1 we're gonna need `Diagnostics` as well. 

The initial set of phases should be:

* `integration`
* `production`
* `diagnostics`
* `decommissioned`

with devices defaulting to / starting in `integration`. 

The new endpoints should be:

* `GET /device/:id/phase`
Which will retrieve the current device phase as a document like `{ "id": "8078bd25-4181-4059-9cf8-01a663fea9e4" , "phase": "integration" }`
* `POST /device/:id/phase`
Takes a document like `{ "phase": "production" }`. Will allow changing the device phase to one of the above choices, and will upon success return the same structure as above with the new phase.

We should report the phase in the DetailedDevice response as well.

**Comment by karenetheridge** [comment]
> with devices defaulting to / starting in `integration`.

What do you mean by `/` here?

**Comment by perigrin** [comment]
I mean I'd probably implement this as a default value for the column, but whatever works so that devices start in the right state is fine by me.
