### ISSUE TITLE
Expose metrics in Prometheus format

### ISSUE THREAD

**Issue by sungo** [joyent/conch#623]
Previously, we've discussed edge clients posting metrics into the Conch API, with those metrics immediately sent to an external system like Prometheus or Circonous. It would be far easier for us to offer metrics as a Conch API endpoint that can be polled by a system such as Prometheus or Circonous.

Happily, both Prometheus and Circonous support the Prometheus data format and offer polling abilities. Further, a Perl module exists ( `Net::Prometheus` ) with a Mojo plugin on offer as well ( `Mojolicious::Plugin::Prometheus` ).

The Conch API needs to expose metrics in the Prometheus data format. 

Initial metrics should be:
* Counter: HTTP Requests
* Counter: Device Reports Received
* Counter: Device Reports that failed validation
* Counter: Device Reports that passed validation

I do not expect this to be the full list but it will get us started.

**Comment by karenetheridge** [comment]
If the same endpoint is to be used for local (api instance-specific) data such as http requests, as well as system-wide data such as device temperatures, there will need to be an argument in the endpoint that specifies the scope of the data requested.  Some data will be coming from local memory and every api endpoint will need to be polled (e.g. by asking ngnix for all the hosts), and some data will just require one request to the generic api URL.

It will probably be easier to separate these into separate endpoints - one (or more?) for local data and one (or more?) for system-wide.

**Comment by sungo** [comment]
Each API instance should report on only the data it has seen. The applications polling the API should and, in all proposed cases, can handle this situation, aggregating or summarizing the data as appropriate.
