### ISSUE TITLE
remove 'validated' field and endpoints that set/get it

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch#640]
as per:

https://github.com/joyent/conch-livesys/issues/97
and
https://github.com/joyent/conch-relay/issues/168

the 'validated' ~~flag~~field on the device adds no value and can be misleading, as it is actually orthogonal data to the 'health' column (which tracks validation results). Remove it from the database and the endpoints that set/get it.

**Comment by sungo** [comment]
Dupe of https://github.com/joyent/conch/issues/532.

'validated' is also not a flag. It's a timestamp which has use cases. Specifically wanting to know when a host passed validation. (Yes, I know that 'when' is an interesting question. Let's go with "most recently")

**Comment by karenetheridge** [comment]
It adds no value, as we can find that information by searching for the last passing report (which we will be retaining even after applying the new retention logic).  It's not tracking that specific data though -- all it's tracking is "when did someone hit the `device/:id/validated` endpoint, which might be something totally different. A reporter should not have to hit this endpoint when it gets a passing result from submitting a report.

**Comment by sungo** [comment]
I understand that. My point is that having access to a single timestamp of 'validated' is useful. Yes, one can get it from looking at the device reports or validation states. Right now, though, a device response comes with a timestamp indicating when the device was validated and that is super handy.

Currently, to get that same information from the API, I need to make two hits. one to get the device, another to get the validated states.

**Comment by sungo** [comment]
Continuing conversation in #532

**Comment by karenetheridge** [comment]
I added comments to 532 and will delete this ticket if github lets me.
