### ISSUE TITLE
Unexpected racks appearing in workspaces

### ISSUE THREAD

**Issue by perigrin** [joyent/conch#643]
When a client issues a `GET /workspace/:wid/rack` request, the API returns devices that don't have a direct relationship with that workspace. A subsequent to `GET /workspace/:wid/rack/:rid` where :rid is the UUID for one of these racks returns a 404.

Workspaces should only display the racks they have a direct relationship with (either because they have a common row in workspace_datacenter_rack or because the rack has a room_id that has a common row with the workspace in workspace_datacenter_room.

If a rack does appear in the results from `GET /workspace/:wid/rack` then it SHOULD always return valid results for `GET /workspace/:wid/rack/:rid` and not a 404.

**Comment by karenetheridge** [comment]
This is a regression starting in version 2.22.
