### ISSUE TITLE
Add rack_id to Device response

### ISSUE THREAD

**Issue by sungo** [joyent/conch#644]
Subject says it all. I'd like to get the rack UUID for a device back anywhere the Device response schema is used. The field should be null or all-zeros UUID if the device has no location. (Implementor's choice there. The go parser will turn it into an all-zeros UUID for me regardless)

This is specifically in support of joyent/conch-shell#227 where I need to do a DetailedDevice or Location lookup for every device in a workspace just to get its location.

If the API provides the rack id, I can do the follow-on lookups separately, caching as I go. For instance, if 20 devices in a workspace are in the same rack, I will only need to make one API call where currently I make 20.

**Comment by karenetheridge** [comment]
do you want rack_unit_start along with rack_id?

**Comment by sungo** [comment]
Sure. Since you've got it in the row, might as well
