### ISSUE TITLE
Add CPU data to DetailedDevice

### ISSUE THREAD

**Issue by sungo** [joyent/conch#649]
Device reports contain a `cpus` array and I'd like that data exposed in the DetailedDevice response

**Comment by karenetheridge** [comment]
We have two main options here: figure out where (and how) to store cpu data into the database (a new device_processor table, it would seem), or that endpoint can rip the data directly out of the latest device report (ew!).

Either way we'll need to formalize in the DeviceReport schema what structure this data should have, and also what this data should look like when returned in DetailedDevice.

**Comment by sungo** [comment]
This data is already specifically covered in in #551. I'm going to close this ticket, since it is essentially a dupe.
