### ISSUE TITLE
Add DIMMS data to DetailedDevice

### ISSUE THREAD

**Issue by sungo** [joyent/conch#650]
The device reports contain a `dimms` element and I'd like that exposed in the DetailedDevice response

This obsoletes #552

**Comment by karenetheridge** [comment]
I think we need to write a spec for this section of the device report first, to be sure of what data we can expect as well as the format that it is in.

e.g. looking at the structure as shown in #672,
- is serial-number globally unique, or just unique for this device?
- can we infer a slot number from anything?
- any expected formats for memory size, type..?

**Comment by sungo** [comment]
This data is already specifically covered in in #551. I'm going to close this ticket, since it is essentially a dupe.
