### ISSUE TITLE
New endpoints for assigning devices to racks

### ISSUE THREAD

**Issue by sungo** [joyent/conch#654]
Currently, devices are assigned to racks using `/workspace/:id/rack/:id/layout`. It accepts a payload that looks like `{ "device_id": 47 }`

The current endpoint has a few problems that I'd like to resolve:
* Requires a workspace 
* The payload is unfortunate
* The UI now offers the ability to update a device's asset tag during this stage

To resolve these issues, I'd like:
* Use new endpoints - this prevents breaking the web UI
* Not require a workspace - Since the user may have the ability to write to a rack via several workspaces, I'd like the API to resolve those permissions internally, rather than have to figure out an appropriate workspace for every operation
* Allow setting a device's asset tag in the same operation as assigning it to a rack slot
* Use a new payload which I will detail below.

I suggest:
* `GET /rack/:id/assignment` - returns the current rack configuration
* `POST /rack/:id/assignment` - updates the current rack configuration, assigning devices as necessary
* `DELETE /rack/:id/assignment` - deletes devices from rack slots

The GET payload would look like: 
```
[
  {
    "rack_unit_start": 47,
    "device_id": "SN1234",
    "device_asset_tag": "JOY1234",
    "hardware_product": "friendly-name",
  },
  {
    "rack_unit_start": 45,
    "hardware_product": "friendly-name",
  },
]
```

The POST payload would look like:
```
[ 
  { 
    "device_id": "SN1234",
    "rack_unit_start": 47,
    "device_asset_tag": "JOY1234",
  },
  {
    "device_id": "SN1235",
    "rack_unit_start": 45,
    "device_asset_tag": "JOY1235",
  },
]
```
* asset tags should be optional

The DELETE payload would look like:
```
[
  {
    "rack_unit_start": 47,
    "device_id": "SN1234",
  },
]
```

**Comment by sungo** [comment]
I was wrong about the current payload so I updated the original description with the correct information

**Comment by karenetheridge** [comment]
I see there is no permissions checking on the existing `/rack/:id` endpoints, so I will fix that (looking for GET->ro, POST/DELETE->rw permissions on any workspace(s) the racks are located in) as well.

For the POST endpoint, I will treat asset_tag as an optional field but device_id and rack_unit_start as required.

For POST, should we permit moving a device from a previously-assigned location (possibly a different rack entirely), or should it have to be explicitly removed from that location first before being assigned to a new location?

**Comment by perigrin** [comment]
Required fields should be `rack_unit_start AND (device_id OR asset_tag)` I believe.

I'd start with require a DELETE and throw an error if a device is already assigned and you try assigning it to somewhere new. If we end up talking about automating that in the clients we can automate it in the API instead (possibly with a force=1 flag or something).

**Comment by karenetheridge** [comment]
We can't make device_id optional, because asset_tag isn't guaranteed to be unique. Should it be?

```
conch=# select count(*) from (select asset_tag, count(*) as count from device group by asset_tag) d where count > 1;
 count 
-------
    16
(1 row)
```

**Comment by sungo** [comment]
@perigrin I disagree. The device ID is the primary key in `device` and, last I knew, we autocreate devices in there. The device id should always be provided.

@ether moving devices like that feels ... unexpected to me and it'd be easy for a user to do it by mistake. The shell implementation of this will use json blobs and it'll be easy for a user to oops by copy and pasting. I'd prefer the API throw an error if the user attempts to change the device's `rack_unit_start`

**Comment by perigrin** [comment]
@sungo I thought the device_id was optional in the current UI, turns out I was wrong. Then @karenetheridge is correct and `asset_tag` should simply be an optional field there.

**Comment by karenetheridge** [comment]
In `GET /rack/:datacenter_rack_id/layouts`, I have a comment: 

```
    # TODO: to be more helpful to the UI, we should include the width of the hardware that will     
    # occupy each rack_unit(s).
```

..and I agree with that sentiment.. so I would suggest adding `rack_unit` to the results of the GET payload described above.

**Comment by karenetheridge** [comment]
In responses, is only including the `hardware_product`'s name, not its id, unfriendly to anyone/thing that then wants to operate on that `hardware_product`? It would need to do another query to find its id.

So, should it instead be `hardware_product_id` and `hardware_product_name`?

**Comment by sungo** [comment]
hardware products can be looked up by name, yes?

In both the web UI and the shell, we already display the hardware product name and it's the value used in the current workspace endpoint. If the payload provides only the product ID, both tools will need to additional lookups.

**Comment by karenetheridge** [comment]
Here's another wrinkle: we permit putting a device into a particular location even if it is the wrong hardware product (that is, we don't check that `device.hardware_product_id` matches `device->device_location->datacenter_rack_layout->hardware_product_id` until validation time.  So in the GET response, do we include the device's hardware_product, or the layout's hardware_product, or perhaps even both? ew ew ew.

Alternatively we could, in this endpoint, prohibit assigning a device to a slot allocated to a different hardware product.

**Comment by sungo** [comment]
I think the current endpoint returns the hardware product from the layout which, in general, is what I'd expect.

**Comment by karenetheridge** [comment]
yes, we can look up hardware products by id or name (and sku or alias too). so ok, just the name should be fine then.
