### ISSUE TITLE
Forge validation states for old device reports

### ISSUE THREAD

**Issue by sungo** [joyent/conch#660]
With the new retention policy, we're looking to purge old records that don't meet the new "keep" requirements. For records that predate the current validation system, this is difficult since they lack validation state records. We don't know which are passing, failing, etc. We can't run them back through the current validation system as backwards compatibility has been broken several times since then.

It should be possible, however, to forge validation state records using the old device_validate table. We purged that table out of production back in August but the data still exists as a backup in manta.

I recommend we load that backup into a dev instance someplace and use the data to create validation states for all the old device reports, importing those states back into production. I'd like to keep the original date if we can, rather than creating them with $today's date.

**Comment by karenetheridge** [comment]
Looks like this should have been done before #397, but it was not identified as still outstanding. A pity!
