### ISSUE TITLE
Add roomid to workspace rack query

### ISSUE THREAD

**Issue by bdelano** [joyent/conch#661]
Can we include the room id when doing a list of racks per workspace?  This would allow us to easily associate racks with rooms and would avoid folks having to include a room reference in the rack name e.g. `3.1-0905`.  

`https://conch.joyent.us/workspace/ap-southeast-1-exp1p2/rack/47caeaf6-9393-4d29-8cde-a14a35762077`

use case:
I am currently working on audit between netbox and conch and this would go a long way to helping me line things up.  

Also, in the future I may want to rely on conch to pull new rack information into netbox and when this happens it is extremely important that I have a 1:1 correlation between room and rack names so I can easily update between the 2.

**Comment by sungo** [comment]
Is this a situation that can be better facilitated by the shell?

**Comment by bdelano** [comment]
I am only using the shell to get login details.. then I am interacting directly with the api via python script

**Comment by karenetheridge** [comment]
The naming is a bit strange due to historical reasons, but the 'datacenter' field in the response is actually `datacenter_room.az`.

**Comment by sungo** [comment]
`GET /rack/:id` if one has the right permissions, uses the Rack json response which contains the datacenter room ID.

**Comment by karenetheridge** [comment]
@bdelano is the existing endpoint `GET /rack/:id` sufficient for you? It returns https://github.com/joyent/conch/blob/master/json-schema/response.yaml#L1254-L1288

**Comment by perigrin** [comment]
Assigning to @bdelano to track the answer to the question.

**Comment by bdelano** [comment]
I'm getting what I need from /room so closing this down
