### ISSUE TITLE
Add custom endpoint(s) for PXE data

### ISSUE THREAD

**Issue by jemershaw** [joyent/conch#663]
This data below needs to be returned from a workspace point of view and the device endpoint.
```json
[
  {
      "id": "device1",
      "location": {
        "datacenter" : {
          "name" : "datacenter1", // datacenter/region name
          "vendor_name": "room.name" // Room/Cage name
        },
        "rack" : {
          "name": "rack1", // Rack name
          "unit": 1 // Rack RU Number
        }
      },
      "pxe": {
        "mac": ":mac" // see pxe_mac function example
      },
      "ipmi": {
        "mac": ":ipmi_mac.mac", // see ipmi_mac function example
        "ip": ":ipmi_mac.ip" // see ipmi_mac function example
      }
  },
  {
      "id": "device2",
      "location": {
        "datacenter" : {
          "name" : "datacenter2", // datacenter/region name
          "vendor_name": "room.name" // Room/Cage name
        },
        "rack" : {
          "name": "rack2", // Rack name
          "unit": 3 // Rack RU Number
        }
      },
      "pxe": {
        "mac": ":mac" // see pxe_mac function example
      },
      "ipmi": {
        "mac": ":ipmi_mac.mac", // see ipmi_mac function example
        "ip": ":ipmi_mac.ip" // see ipmi_mac function example
      }
  }
]
```

```js
function pxe_mac(nics) {
  return nics.sort(function(a,b){
    if(a.iface_name> b.iface_name){
      return 1;
    }
    if( a.iface_name < b.iface_name){
      return -1
    }
    return 0;
  }).filter(function(nic) {
    if( nic.state == "up"){
      return nic.mac
    }
  })[0];
}

function ipmi_mac(nics) {
  return nics.filter(function(nic) {
    return nic.iface_name == "ipmi1"
  })[0];
}
```

In English: 

The `pxe_mac` is the mac address from the first interface sorted asciibetically who's status is "up" .

The `impi_mac` is the mac address from the interface named `impi1`.

**Comment by karenetheridge** [comment]
I'm not really sure what you're asking for here. Reading https://en.wikipedia.org/wiki/Preboot_Execution_Environment hasn't helped. :)

**Comment by karenetheridge** [comment]
If the desired data is similar to existing endpoint(s) (e.g. just additional data to be included), it might be better to add a `?with_pxe` parameter instead of creating entirely new endpoints to convey this.

**Comment by karenetheridge** [comment]
@jemershaw Please also clarify that you are referring to the `GET /device/:id` and `GET /workspace/:id/device` endpoints, and that the only changes to those endpoints' output are the addition of the `pxe` and `ipmi` fields (i.e. you haven't added or changed any of other other fields).  Would it be sufficient to add a `?with_pxe` option to those endpoints to signal the inclusion of that data?

**Comment by karenetheridge** [comment]
I should note that (device_id + iface_name) is not a unique index on device_nic, so there is no guarantee that there aren't stale/duplicate entries in the device_nic table and that you'll get the desired result back.

**Comment by jemershaw** [comment]
@karenetheridge: Correct those are the two endpoints that would need this expected output, but it should only contain what is in the json blob. If it was a query parameter then I think adding it to the exiting results from `GET /device/:id` we might want to make sure those output fields are unique. We shouldn't have duplicate entries for the device_nic table since we are reporting this from the os and there shouldn't be duplicate interfaces names, but +1 to force it to be unique.

**Comment by karenetheridge** [comment]
Also note that we already support `GET /device/:id/interface/ipmi1`.

**Comment by karenetheridge** [comment]
@jeff: is the location information absolutely necessary in the response? fetching this for every device in a workspace (which can potentially be the entire database, if GLOBAL is requested) is a hugely expensive query.

**Comment by karenetheridge** [comment]
@jemershaw: is the location information absolutely necessary in the response? fetching this for every device in a workspace (which can potentially be the entire database, if GLOBAL is requested) is a hugely expensive query.

**Comment by bdelano** [comment]
> @jemershaw: is the location information absolutely necessary in the response? fetching this for every device in a workspace (which can potentially be the entire database, if GLOBAL is requested) is a hugely expensive query.

Just curious why this would be costly assuming that this will be pulled 1 device at a time?

e.g.
```
select 
d.id,i.iface_name,i.ipaddr,r.name,dl.rack_unit_start,rm.vendor_name as room,dc.region
from device as d 
join device_nic as i on i.device_id=d.id 
join device_location as dl on dl.device_id=d.id
join datacenter_rack as r on r.id=dl.rack_id
join datacenter_room as rm on rm.id=r.datacenter_room_id
join datacenter as dc on dc.id=rm.datacenter_id
where d.id='4BYNMK2' and iface_name='ipmi1';
```

**Comment by karenetheridge** [comment]
That query doesn't provide the information requested.  Also, workspaces are recursive, and contain rooms as well as racks. Subselects are involved in pulling all the data together, and when requesting information about many devices, this can add up to a very large number of subqueries.  We don't even get location data about a single device in the same query anymore, because we ran into performance issues.

**Comment by jemershaw** [comment]
@karenetheridge -- yes the location is important for this endpoint. Different types of configuration would be applied based on the physical location of the device.
