### ISSUE TITLE
Add latest_report_is_invalid to /workspace/:id/device response

### ISSUE THREAD

**Issue by dustinryerson** [joyent/conch#666]
As of right now, it seems that `latest_report_is_invalid` is only available at `GET /device/:id`. This is great because I can flag invalid devices on the device inspector (the display that appears after _clicking_ a device). However, I'd also like to be able to surface invalid device flags without requiring a user to click on the device.

My goal is to make it easy to find invalid devices, without requiring the user to hunt them down individually by clicking through them. Both the DataCenterBrowser and DeviceBrowser components of the UI use the `/workspace/:id/device` endpoint to populate device lists, which is where I'd like to add invalid device flags.

One option I have is to hit the `GET /device/:id` endpoint for each device returned from `/workspace/:id/device`, but that seems expensive just to get data from one field. However if this would be the preferred method, I can move forward with it.

**Comment by karenetheridge** [comment]
Adding this would result in this endpoint being really really slow, because a separate query needs to be done for every device in the result (finding the latest report for each device).  Would you need this field for *every* device all the time, or just some of them some of the time?  (That is, if we can skip fetching this information when it's not needed, all callers will be happier.)

**Comment by karenetheridge** [comment]
Also note that "the device failed its validation" is not the same as the `latest_report_is_invalid` flag. The latter merely means "the report didn't match the expected json schema so we couldn't even run validations on it".  Do you perhaps want `device.health` instead, which is already included in the result and contains the results of the most recent validation run?

**Comment by dustinryerson** [comment]
Ah ok, that makes sense. This request is for https://github.com/joyent/conch-ui/issues/52, which referenced https://github.com/joyent/conch/pull/533, which added `latest_report_is_invalid`. So I'm specifically looking for those devices whose latest reports didn't match the expected json schema. I was thinking I'd need the field for some/all of the devices some of the time, depending on which workspace is selected. So at times it could be a few hundred devices, or a few thousand. Although it sounds like the better option might simply be to hit the `GET /device/:id` endpoint to get the field rather than making the `/workspace/:id/device` endpoint really really slow.

**Comment by karenetheridge** [comment]
`GET /device/:id` returns lot more things though, so if you're going to do that anyway for all of your thousands of devices, it ends up being even more expensive still.

What exactly do you need to do for #52? The ticket I filed was just letting you know that additional data was going to start being returned in `GET /device/:id` -- I have no strong feelings about surfacing that in workspace-scoped views of devices.

**Comment by dustinryerson** [comment]
I was working based off a few comments I read on the original issue:
1. https://github.com/joyent/conch/issues/377#issuecomment-418395350
2. https://github.com/joyent/conch/issues/377#issuecomment-435121300

However if this kind of enhancement in unnecessary, that's totally fine and we can close this.

**Comment by perigrin** [comment]
@dustinryerson I think for 2.23 compatibility we can leave this open for now but close  [joyent/conch-ui#52](https://github.com/joyent/conch-ui/issues/52) as a no-op since AFAIK the UI doesn't currently use the `/device/:id` endpoints at all.

That said I do think surfacing the `latest_report_is_invalid` data at the workspace-at-a-time level is something we should talk about.

**Comment by karenetheridge** [comment]
In v3 we won't be saving invalid reports at all (#804). closing.
