### ISSUE TITLE
Need DimmCount validation to count populated DIMM slots

### ISSUE THREAD

**Issue by daleghent** [joyent/conch#672]
As an oversight on my part when reviewing the recent DIMM (and CPU) changes to validations, we're now counting all DIMM slots on the system instead of _populated_ DIMM slots. We need to convert the `dimms` array member count to count only members which have a hash that exists only in populated DIMM slots. Here are examples of a populated and unpopulated DIMM slot:

```
    {
      "memory-asset-tag": "001606C0",
      "memory-bank-locator": "Not Specified",
      "memory-configured-clock-speed": "2400",
      "memory-configured-voltage": "1.2",
      "memory-data-width": "64",
      "memory-form-factor": "DIMM",
      "memory-locator": "B8",
      "memory-manufacturer": "00CE063200CE",
      "memory-maximum-voltage": "1.2",
      "memory-minimum-voltage": "1.2",
      "memory-part-number": "M393A2K43BB1-CRC",
      "memory-rank": "2",
      "memory-serial-number": "31830551",
      "memory-set": "5",
      "memory-size": 16,
      "memory-speed": "2400",
      "memory-total-width": "72",
      "memory-type": "DDR4",
      "memory-type-detail": "Synchronous Registered (Buffered)"
    },
    {
      "memory-asset-tag": "Not Specified",
      "memory-bank-locator": "Not Specified",
      "memory-locator": "B9",
      "memory-manufacturer": "Not Specified",
      "memory-part-number": "Not Specified",
      "memory-serial-number": "Not Specified",
      "memory-set": "6"
    }
````
To know that a given DIMM slot is populated, we should look for the presence of any of `memory-size` or `memory-type` and tally those, as that data _should not_ exist in non-populated slots.

**Comment by karenetheridge** [comment]
Could you clarify which validation(s) are being talked about here?

**Comment by perigrin** [comment]
I believe it was the ones I changed in PR#634
