### ISSUE TITLE
Lock Workspaces to Racks not Rooms

### ISSUE THREAD

**Issue by perigrin** [joyent/conch#679]
Workspaces and Rooms are orthogonal concepts. While both are collections of racks,
Rooms represent a physical artifact (there is in fact a Room somewhere in the real 
world that has racks in it) while Workspaces are entirely ephemeral collections 
of racks that only exist in Conch.

Currently workspaces have two pivot tables that define their contents,
`workspace_datacenter_rack` and `workspace_datacenter_room`. The latter should
be dropped, possibly replaced by a couple of helper functions that would allow
easily adding and removing rooms full of racks to a workspace. 

The trigger that adds rooms to the GLOBAL workspace upon creation would need to 
be reworked to add racks to GLOBAL instead.

Going forward, workspaces should **only** be _virtual_ containers of racks.

This means that the `/workspace/:id/rooms` endpoint should be purged entirely 
and preferably return a 410 GONE. 

All existing racks associated with workspaces via rooms should be added to 
the workspaces directly. This means all 10K+ racks should be added to GLOBAL
and probably a function/trigger `add_rack_to_global_workspace()` should be 
created to replace the existing `add_room_to_global_workspace()` function/trigger.

**Comment by bdelano** [comment]
not that i will ever use the functionality... but why would we not just keep the add_room endpoint but have it then use add_rack for all racks associated with that room?

**Comment by perigrin** [comment]
Easier to just replace it with a trigger on the rack table. That way if for some reason racks in the future can be created for some reason without a room you don’t have a bug where they don’t end up in GLOBAL.

**Comment by sungo** [comment]
Like this one? https://github.com/joyent/conch/blob/master/sql/migrations/0012-workspaces.sql#L71

**Comment by bdelano** [comment]
@perigrin not sure why a rack would ever be created without a room, but i think we just just make it mandatory if its not already...

**Comment by perigrin** [comment]
Well case in point I don't know if the integration facility currently counts as "a room". Also as we expand the contents of rooms past simply racks the question becomes more nuanced.

**Comment by perigrin** [comment]
@sungo that trigger is the one I specifically cited in the ticket. So yes exactly like that one, changed and renamed way I suggest in the ticket.
