### ISSUE TITLE
Ability to retrieve a validation state by its ID

### ISSUE THREAD

**Issue by sungo** [joyent/conch#686]
`POST /device/:id` returns a validation state. To get more data about that state, I need to look up that record.

Currently, I cannot retrieve a validation state by its ID. I must know the relevant device ID, `GET /device/:id/validation_state`, and hope that the most recent state is the one I have.

I need a way to access a validation state using its UUID.

**Comment by karenetheridge** [comment]
I'm going to assume that ValidationStateWithResult is the right set of data you're after. Let me know if you want bits of the device report, validations, etc mixed in.
