### ISSUE TITLE
Should probably send email when the user's password is changed

### ISSUE THREAD

**Issue by sungo** [joyent/conch#694]
A general notification email that a user's password has been changed seems like a reasonable precaution.

**Comment by karenetheridge** [comment]
Do you mean to the user in question, or admins?  We do send an email to the user when someone's password is changed -- https://github.com/joyent/conch/blob/master/lib/Conch/Controller/User.pm#L263

**Comment by sungo** [comment]
That email is being sent from when the user's password is reset, not when it's changed in `change_own_password`. The vector here is that a person obtains another user's credentials and changes the password to lock that user out of their account.
