### ISSUE TITLE
Ability to check for the existence of any device, regardless of location

### ISSUE THREAD

**Issue by sungo** [joyent/conch#695]
Right now, there appears to be no way to get an HTTP 200 back from `GET /device/:id` for any device in the database. The device must be located to a workspace that the user can see or reported using a relay associated with the user's account. I need a way for some user type, probably admin sadly, to `GET /device/:id` for any device in the database, regardless of its location or workspace assignment.

**Comment by karenetheridge** [comment]
To summarize the various options we have available to us in the near term:

- add an entry to `user_relay_connection` when processing device reports. This will let the user who sent the report see information about that device (and any other device it sent reports for)
- add a check for `$user->is_system_admin` for all `/device/:id/*` endpoints (excluding device report submission itself) - this is in Conch::Controller::Device::find_device

**Comment by karenetheridge** [comment]
Is relay_id present in most of the reports you're working with? I have no idea how prevalent it is, but would expect that livesys and reporter code do generally add it.

**Comment by sungo** [comment]
I don't know. I'm either extracting them from the database or accepting whatever the user provides on the cli.
