### ISSUE TITLE
`conch-db all` shouldn't error out

### ISSUE THREAD

**Issue by sungo** [joyent/conch#698]
`conch-db all` runs initialize every time. After the first run, that errors out because the database exists and has tables in it.

It'd be nice to be able to run `conch-db all` repeatedly without that error. 

My main use case is inside the docker environment where I'd like to always run `conch-db all` after a code update to can ensure the database is in proper form, rather than worrying about if I need to call some validations command or the migration command or what.

**Comment by karenetheridge** [comment]
I'm not sure what you intend `conch-db all` to do, if not initialize a new db? That's what `all` is documented to do (in part).

**Comment by karenetheridge** [comment]
`all` is documented to initialize a db. Perhaps you want `conch-db migrate`?

**Comment by sungo** [comment]
partially. the larger picture is #635 but in this specific case, it'd be nice for `all` to not error if the database is initialized properly. I could then string the individual db commands together.

**Comment by karenetheridge** [comment]
Right now `all` calls `initialize`. I'm not sure how `initialize` would be able to tell that you've already got `sql/schema.sql` loaded and it doesn't need to do it again.  I suppose it could look for the presence of the `migration` table, which should always be there, but that's not really "initialize my db" anymore but "initialize my db unless it already exists". I can add that command and then `add` can call that instead (or, add a flag -- naming suggestions welcome) that requests that check.

i.e.

    bin/conch-db initialize --> db should be empty; errors otherwise
    bin/conch-db initialize --dont-do-twice    --> checks for migration table first, and does nothing if it is already there
