### ISSUE TITLE
Ability to run conch api on a read only filesystem

### ISSUE THREAD

**Issue by sungo** [joyent/conch#699]
I cannot currently run the Conch API inside a read-only docker container.

The first failure I've run into is that `Capture::Tiny`, used in `Conch::Plugin::GitVersion` to record git information about the application, writes temporary files.

I'm not sure if there are other cases yet.

**Comment by karenetheridge** [comment]
I can patch around this particular occurrence, but we may hit obstacles within Mojolicious.
