### ISSUE TITLE
Recurring error in console

### ISSUE THREAD

**Issue by dustinryerson** [joyent/conch#713]
**Error:**
```
Use of uninitialized value in uc at conch/lib/Conch/Controller/WorkspaceRack.pm line 57
```

**Line of code referenced in error:** https://github.com/joyent/conch/blob/master/lib/Conch/Controller/WorkspaceRack.pm#L57

**Comment by sungo** [comment]
I *think* we're just missing a set of parens there.

I'm concerned the error is not showing up in the tests, particularly since there's an explicit test for warnings. @perigrin, any thoughts?

**Comment by perigrin** [comment]
Yeah the precedence on the uc isn’t including the // would be my guess too. Lemme look at the tests to see why they’re not whining, my assumption is we always provide a status in them so never trigger this case.

**Comment by karenetheridge** [comment]
I don't see how this can be happening, since `device.health` is a not-nullable field. Dustin, was this happening locally, or on staging/production? What workspace were you querying for at the time?
