### ISSUE TITLE
Convert all embedded json schema definitions into distinct entities

### ISSUE THREAD

**Issue by sungo** [joyent/conch#715]
An example is `DeviceLocation.target_hardware_product` currently at https://github.com/joyent/conch/blob/master/json-schema/response.yaml#L601

Another example is `WorkspaceRack.slots` currently at https://github.com/joyent/conch/blob/master/json-schema/response.yaml#L866

In these cases, the structure represents a single entity but is embedded inside the parent entity. In general, these are single use entities so I understand why they are inlined currently. 

For the shell, life is much easier if these are independent constructs and most of the structures already are independent structs in the shell's conch lib. I'd like to make this official on the API side so I can reference schema entities for each struct.

**Comment by karenetheridge** [comment]
I'm not sure that anything additional needs to be done here to achieve your request  -- if your references are simply documentation/comments etc, you should be able to formally reference a section of a schema via its official json pointer, e.g. `response.yaml#/definitions/DeviceLocation/properties/target_hardware_product`.

Are you wanting to write Go code that extracts a schema for comparison e.g. in tests?  e.g. `GET /schema/DeviceLocation_target_hardware_product`?

**Comment by sungo** [comment]
auto-generation of structs is certainly a possibility. 

but consider the following structures:
https://github.com/joyent/conch-shell/blob/master/pkg/conch/structs.go#L132

your "target_hardware_product" becomes
https://github.com/joyent/conch-shell/blob/master/pkg/conch/structs.go#L275

your `target_hardware_product` is a sub-structure that could stand alone. It is a distinct concept, not a property of a device's location.

I am asking for these sort of single-use-but-distinct concepts to be made their own structures in the json schema.
