### ISSUE TITLE
Send email to a user when their account is changed in any way

### ISSUE THREAD

**Issue by sungo** [joyent/conch#716]
Admins have the ability to make all sorts of changes to a user's account. Also, obviously, the user has the ability to change their account, particularly their password.

It would improve the user experience if the user's got email when these actions occurred.

Use cases:
* An admin promotes a user to or demotes them from system admin status
* A system or workspace admin adds a user to or removes a user from a workspace
* A system or workspace admin alters the permissions of a user on a workspace
* The user's password is changed, by anyone including themselves. We should include the user on the off-chance that their account was compromised and a third-party is changing their password.
* The user's email address is changed. Send email to both the old and new accounts.

Sending these emails would improve transparency and let a user know why their lives have changed, particularly when it comes to permissions changes. _(Currently, an admin can change a user's permissions and change the data that the user is allowed to see. Since the user is never notified, automations may break or wat may occur.)_

The emails should look something like
```
From: conch
To: user
Subject: Your [password, email address, permissions, etc] have changed

Just letting you know that [action was performed] on your account. If you feel this is in error, please contact a conch admin.
```

Supersedes and closes #694

**Comment by karenetheridge** [comment]
Should we tell the user about revocation of their tokens (api and/or login)?

**Comment by sungo** [comment]
@karenetheridge yes. since the revocation of API tokens in particular will break automated scripts, it'd be good for a user to receive notification.

**Comment by karenetheridge** [comment]
I need email copy for these situations (assume the existence of relevant stash variables for filling in a template):

- an admin revoked a user's tokens (can be login, api, or both) - which means they need to go to `POST /login` again before doing anything else
- an admin updated a user's account (any of: changed name, changed email, toggled is_admin flag)
- an admin deactivated a user's account (it is no longer usable)
- an admin expired an api token

Also, we don't currently support an admin creating/updating/deleting a user's setting keys, but this is trivial to implement, so if we want to add those routes, we should send email for those as well.
