### ISSUE TITLE
Does anything use the Device json schema?

### ISSUE THREAD

**Issue by sungo** [joyent/conch#720]
Recently, we changed the content of DeviceLocation. In the process we lost "rack unit start". Before filing any other GHI, I wanted to see if that data could be obtained elsewhere. I found the field on the Device schema but it appears that Device is unused. Can someone confirm my finding?

**Comment by karenetheridge** [comment]
The `Device` schema is used in these endpoints:

```
GET /device?hostname=$hostname
GET /device?mac=$macaddr
GET /device?ipaddr=$ipaddr
GET /device?$setting_key=$setting_value
GET /workspace/:workspace_id_or_name/device?<params>
GET /workspace/:workspace_id_or_name/relay/:relay_id/device
```

**Comment by sungo** [comment]
Thanks.
