### ISSUE TITLE
Resetting a user's password should not silently destroy API tokens

### ISSUE THREAD

**Issue by sungo** [joyent/conch#729]
When we patched in the API token system, we did it as an extension of the existing JWT auth system. As such, when a user resets their password, the API destroys all outstanding tokens, including their tokens.

I would like the user to have to opt-in to that behavior. Many sites with API tokens have a tickey box on their password change form like `[ ] also remove all API tokens? (this cannot be undone)`. While that's obviously a conch-ui ticket, the API needs to support that behavior, probably as a query param on the endpoint for resetting one's password. 

I would like the existing admin-style "revoke tokens" behavior to remain. When an admin revokes a user's tokens, it should revoke both login and token JWTs. This endpoint is most useful in a security context so it makes sense to me for an admin to torch all the JWTs for a user in a single hit.

**Comment by karenetheridge** [comment]
We do have `?clear_tokens=<0|1>` on the password reset flows, but we don't differentiate between login tokens and other (api) tokens. I can make this query parameter more nuanced to differentiate them, with the default being "clear login tokens only".
