### ISSUE TITLE
New Phase for Onsite Installation

### ISSUE THREAD

**Issue by perigrin** [joyent/conch#730]
Immediately after #725 was opened we had a request for comparing the integration and the onsite installation phase and I failed to notice that latter wasn't in our initial phase list.

We will need to add `Installation` to the list of allowed phases to cover the onsite installation phase.

**Comment by karenetheridge** [comment]
How is "installation" different from "production" (which is in the current list of possible values: 'integration','production','diagnostics','decommissioned')?

**Comment by perigrin** [comment]
Production means we're serving customer requests from the machines and the data stored on the servers must be protected at all costs.

Installation means we are doing the final pre-flight checks before flipping the machines over to production. There is not yet any customer data on the boxes and we can still perform the full range of pre-flight diagnostics and maintenance on them.

**Comment by karenetheridge** [comment]
let's make sure these definitions are documented somewhere. :)

**Comment by perigrin** [comment]
Agreed. I took #471. I'll be sure to add this to the documentation there.
