### ISSUE TITLE
Would it be possible to add "deactivated" to the UserDetailed response?

### ISSUE THREAD

**Issue by dustinryerson** [joyent/conch#731]
The response for `GET /user` is an [array of `UserDetailed` objects](https://github.com/joyent/conch/blob/master/json-schema/response.yaml#L1504). The UserDetailed response does not include the `deactivated` field.

What would the required effort level of adding `deactivated` to the UserDetails response be?

Code reference:
https://github.com/joyent/conch/blob/master/lib/Conch/Controller/User.pm#L343-L357

**Comment by karenetheridge** [comment]
What would this be useful for? the value will be null in all cases, since only active users are returned by this endpoint.

**Comment by dustinryerson** [comment]
Closing since only active users are returned with this endpoint, and reactivating users is not an option and thus doesn't need consideration from the UI side.
