### ISSUE TITLE
Duplicate entry error when editing a user is not the same as when creating a user

### ISSUE THREAD

**Issue by dustinryerson** [joyent/conch#739]
When creating a new user, if I attempt to use an email which is already being used by another user, I get the following error in the response:
```
http://localhost:8080/user 409 (Conflict)
{"error":"duplicate user found"}
```

When attempting to edit an existing user's email to a different email already being used, I get the following:
```
POST http://localhost:8080/user/{userId} 500 (Internal Server Error)
{"error":"An exception occurred"}
```

Would it be possible to make the second error the same as the first since the error is occurring for the same reason in both cases?

**Comment by karenetheridge** [comment]
yes, http 500 errors are never planned, and are a sign that a check wasn't done before the query went to the db and exploded.
