### ISSUE TITLE
Conch::Controller::WorkspaceRack::remove still assumes room<->workspace relationships.

### ISSUE THREAD

**Issue by perigrin** [joyent/conch#745]
Specifically [this code](https://github.com/joyent/conch/blob/master/lib/Conch/Controller/WorkspaceRack.pm#L299-L301) will throw a 409 with an error talking about implicit associations via rooms if somehow the delete returns 0 rows deleted. 

PR https://github.com/joyent/conch/pull/692 removed the room <-> workspace relationship, this bit of code was likely overlooked as it can't (easily?) be triggered anymore.

It should still be cleaned up at some point.

**Comment by karenetheridge** [comment]
yes, that looks like dead code entirely, since `workspace_rack#find_rack` will return 404 earlier on if that rack isn't in the workspace.
