### ISSUE TITLE
POST /reset_password needs attention

### ISSUE THREAD

**Issue by perigrin** [joyent/conch#767]
Currently the implementation is taking a POST request, validating the input arguments and then doing a redirect to `/user/#target_user_id_or_email/password` which only implements a `DELETE` method.  According to [rfc7321 section 6.4.2](https://tools.ietf.org/html/rfc7231#section-6.4.2) this isn't correct the only exception is:

> For historical reasons, a user agent MAY change the request
> method from POST to GET for the subsequent request.

It looks like we *should* be re-directing them to `/user/me/password` instead, and because we don't want them changing HTTP method we should be using `308 PERMANENT REDIRECT` (see [rfc7238](https://tools.ietf.org/html/rfc7238) instead.

Alternatively if we're nobody is using this endpoint anymore, we should just drop it to a `410 GONE`.

**Comment by karenetheridge** [comment]
There is no such endpoint `POST /reset_password` -- which one do you mean?

**Comment by karenetheridge** [comment]
Does it work, at present? Does the redirect work properly and find the correct route?

**Comment by karenetheridge** [comment]
(part of why I ask is to determine if this should be targeted to v2 or v3.)

**Comment by perigrin** [comment]
I can't see how it could __possibly__ work as written since we have no way of signalling the HTTP verb changed, and I've never heard of anything automatically changing a POST to a DELETE when given a 301. 

Neither of our supported client's are currently using it, I suggest we just drop it, and return a `410 GONE` in v2.

**Comment by karenetheridge** [comment]
I'm interested in seeing what happens when someone tries to use it, if anyone cares to test it.
