### ISSUE TITLE
The updated rack is not returned in the response for POST /rack/:rackId/phase

### ISSUE THREAD

**Issue by dustinryerson** [joyent/conch#792]
In a similar request, `POST /device/:id/phase`, the updated device is returned in the response.

If possible, I'd like the updated rack (and the devices in the rack if their phases are updated) to be returned in the response for `POST /rack/:rackId/phase`.

**Comment by karenetheridge** [comment]
`POST /device/:id/phase` returns a 303+`Location: /device/:device_id` -- I can issue a similar redirect response for updating the rack phase.
