### ISSUE TITLE
Include the rack phase in the response for GET /workspace/:id/rack

### ISSUE THREAD

**Issue by dustinryerson** [joyent/conch#793]
If possible, I'd like to have the rack phase returned when I request all the racks for a workspace using `GET /workspace/:id/rack`. This would allow me to include the rack phase on the workspace status page without having to send an individual request for each rack by using `GET /workspace/:id/rack/:rackId`.

**Comment by karenetheridge** [comment]
doh, I missed this one when I did 2.29.1..
