### ISSUE TITLE
detect and reject clients that are too old

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch#802]
to do this, we need to look at request headers that can tell us what kind of client it is, and what version it's at.

for the UI -- see https://github.com/joyent/conch-ui/pull/115

for the shell -- ?? (see also https://github.com/joyent/conch-shell/issues/310)

**Comment by sungo** [comment]
It's not pushed up yet but the conch shell's user agent string will soon look like this:

`Conch/1.12.0 ConchShell/1.12.0 (v1.12.0-7-g50a79c0-dirty; linux; amd64; sungo (1000);)`

The internal library always sets the `Conch/$version` part and this is the important version to filter on. Anything that uses the go lib for accessing the conch api will have that first part. While I don't have a minimum version for you yet, the default, if someone is building the app without using the Makefile is '0.0.0' and it should *always* be rejected. So, refuse to talk to a user agent that starts with `Conch/0.0.0`.

The remainder of the user agent string is primarily for my internal use in logging and the like. Please preserve those bits in the log, as v2 does today, but don't filter on them.
