### ISSUE TITLE
Supporting overwriting all the layouts in a rack in a single operation

### ISSUE THREAD

**Issue by sungo** [joyent/conch#877]
A rack has layouts, which are technically the definitions of what each rack slot should be. (This terminology is kinda awful.) 

There is currently no way, in the API, to overwrite all the layouts in a rack with new data in a single operation. I would like an endpoint that lets me completely overwrite all layouts in a rack with new data in a single operation..

Consider the following code from conch shell:
https://github.com/joyent/conch-shell/blob/master/pkg/commands/rack/rack.go#L404

I have a file from the user that defines the layouts for the rack, specifically what the user wants the rack layouts to look like. I do not accept partial updates.

In the current API, I have to individually delete every existing layout and then individually insert every desired layout. These potentially leads to several undesirable states.
- If something goes wrong in deleting a layout, the rack is left in an inconsistent state
- If something goes wrong in inserting the desired layouts, the rack is left in an inconsistent state
- If another user (or the web UI) access the rack's layouts while the shell is operating, the user will receive an incomplete list of layouts for the rack

The best way to avoid those issues is to perform the delete-then-insert operations inside a database transaction so that any failure leaves the data in a consistent state.

I would suggest the API endpoint look something like:
* `POST /rack/:id/layouts` with the payload consisting of a list of ru_start and hardware_product_id pairs

**Comment by karenetheridge** [comment]
There are a few different scenarios here which need to be handled, if some layouts in the rack have devices already assigned. We could do any of these:

- evict all devices as we delete the layouts, and entirely new layouts will replace them (which may have identical rack_unit_start and hardware_product_ids)
- decline the operation if there are any located devices
- choose either of the two above options, depending on the value of a query param
- do not alter any existing layouts that remain unchanged before and after (which would let located devices remain)

That is -- is there any usecase for adjusting a rack of partially-populated layouts without going entirely scorched-earth on the rack?  This could happen if a rack needs to be modified after preflight has already begun.

I could also add a `DELETE /rack/:id/layouts` endpoint that does just the deletion (with the same list of possible scenarios as above) without adding new layouts, if desired.

**Comment by sungo** [comment]
My current code calls `DELETE /layout/:id` which, I think, removes any device assigned to that slot. For my use case, I need to retain that behavior.

When overwriting a rack's layouts, I expect all devices to be evicted, as you put it. I do not have any use cases that call for partial evictions.

I cannot make use of an endpoint that refuses this operation if there are any device assignments. If that behavior is controlled by a query param, I will always pass in the value that overwrites and evicts everything.

**Comment by karenetheridge** [comment]
> My current code calls DELETE /layout/:id which, I think, removes any device assigned to that slot. For my use case, I need to retain that behavior.

Negative, the operation fails if the slot is occupied: https://github.com/joyent/conch/blob/master/lib/Conch/Controller/RackLayout.pm#L215-L218

**Comment by sungo** [comment]
Fantastic. Then my users have just never tried to update a populated rack. Or they have and just haven't told me. So that's nice.

**Comment by karenetheridge** [comment]
well this is why I asked about the various scenarios above, because the api tries to be conservative about deleting data unless it knows that you really don't mind about the side effects. :)

**Comment by sungo** [comment]
The code and shell feature is written, however, with the assumption of the eviction behavior. The feature is specifically for overwriting a rack's layouts. 

Regardless, even if the API rejects the transaction because of an existing device, it will do so atomically which will preserve the rack.

Fundamentally, that's what I'm looking for. I want to be able to attempt this operation such that a failure doesn't leave a screwed up or partial configuration.
