### ISSUE TITLE
create device+sku in advance of livesys

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch#893]
As discussed:

- something (e.g. netbox, or DCOPS master spreadsheets) will call conch with a serial number + sku, and conch will record this (creating/updating a device in the database)
- livesys will query conch for the sku corresponding to a specific serial number so it can pick its firmware loadout
- when a device report is processed, the corresponding device will now always exist, and the sku must match what conch has on file (else signal an error indicating that the firmware loadout is wrong).

I propose:
* `POST /build/:build_id_or_name/device` - with the payload containing the serial number and sku (submitting multiple devices at once probably makes sense). the device is created or updated.
  * normal response: 204.
  * error responses: 401 if the user cannot authenticate. 403 if the user doesn't have permission for the endpoint (the 'rw' role for the build would make sense here).
* `GET /device/:serial/sku` - get the device's sku (and possibly other relevant device-level fields  (`GET /device/:serial` returns a lot of data, most of which is not relevant at this stage of the process)
  * normal response: 200 plus payload.
  * error responses: 401 if the user cannot authenticate. 403 if the user doesn't have permission for the endpoint (minimum 'ro' role for the build the device is in).

**Comment by daleghent** [comment]
Will a 404 or other sort of error be returned if answering a query to `/device/:serial/sku` can't be satisfied?

**Comment by karenetheridge** [comment]
I'll add some common error conditions above.

**Comment by daleghent** [comment]
👍 let's run with this

**Comment by perigrin** [comment]
I'd like to see @bdelano comment on this too since he'd proposed writing the Netbox <-> Conch bit.

**Comment by bdelano** [comment]
I had a chat with Richard regarding adding a unique build name to the device and he is going to work with his team to figures something out, so we should be good to go with @karenetheridge's  original concept.

**Comment by karenetheridge** [comment]
It's also an option to start off new "buildless" devices in a placeholder build and then move them to where they belong once that's known.

**Comment by bdelano** [comment]
agreed, I got some feedback from Richard today that everything should be in place by the time the next build comes around so hopefully it will be standard process by the time V3 roles out
