### ISSUE TITLE
Create endpoints for build pages

### ISSUE THREAD

**Issue by dustinryerson** [joyent/conch#922]
# Pages
## Build List Page (will be located at `/admin/builds` on the UI)
- List of all builds, including the following for each build:
  - Build ID
  - Name
  - Description
  - Overall Build Progress (devices passing validation?)

## Individual Build Page (will be located at `/build/:buildId` on the UI)
- Details pertaining to the build itself, including:
  - Build ID, Name, Description, Created, Started, Completed, Sign Off Details, etc.
  - Overall Build Progress (devices passing validation?)
  - List of Users and details for each user including:
    - name
    - role
    - organization membership (which is linked to the build)
    - total user count
  - List of Organizations and details for each including:
    - name
    - role
    - total organization count
  - List of Racks and details for each including:
    - name
    - rack room
    - hardware type
  - List of Devices and details for each including:
    - name
    - rack
    - phase
    - health (validation status)
    - sku

**Comment by karenetheridge** [comment]
For builds list page, I can add support for `?with_device_health` to `GET /build`, which will include an aggregate count of device healths with the result like so:

```
{
    error => 0,
    fail => 1,
    unknown => 2,
    pass => 36,
}
```

This will let you present a multi-coloured pie graph showing how many devices are in various validation states.

For individual build page:

- I will add `?with_device_health` to `GET /build/:id`, as above.
- List of Users: build users are already available at `GET /build/:id/user`. If you fetch this endpoint in parallel with the other requests, it will be faster than adding it to the main `GET /build/:id` endpoint. I'm not sure what you mean by user count here?
- List of Organizations: build organizations are supported similarly at `GET /build/:id/organization`. I'm not sure what you mean by organization count here?
- List of Racks: racks don't have one specific hardware type; each RU can have a different sku. I'm not sure what you want to be displaying here.
- List of Devices: `GET /build/:id/device` already includes rack id and RU. I will add rack name to this. (all other rack info should be available by clicking on the rack, I would expect)
The endpoint also already includes hardware_product_id; I will add sku to this as it is more useful to the viewer. (again, I assume the hardware information will be clickable.) phase and health are already included.

**Comment by dustinryerson** [comment]
This all sounds good and gives me the information I need. Thanks!
