### ISSUE TITLE
Add non-workspace-bound GET /device endpoint

### ISSUE THREAD

**Issue by dustinryerson** [joyent/conch#934]
As far as I can tell from looking through the documentation and code, there is no non-workspace-bound (i.e. `GET /:workspace_id/device`) way to get all existing devices.

Since we're moving away from being workspace-focused, I'd like to request a new endpoint to get all devices, something like `GET /device`, similar to the existing endpoints for users, organizations, etc. The response can be identical to the existing `GET /:workspace_id/device` endpoint.

**Comment by karenetheridge** [comment]
What data would you need in the response for that?

**Comment by karenetheridge** [comment]
GET `/build/:build_id_or_name` should operate similarly to the workspace-based endpoint.
