### ISSUE TITLE
GET /user/me endpoint returns duplicate builds

### ISSUE THREAD

**Issue by dustinryerson** [joyent/conch#950]
Here's an image of the builds part of the response:

<img width="735" alt="duplicate_builds" src="https://user-images.githubusercontent.com/2080476/68893686-860f2c80-06da-11ea-9b96-24b5ad47797c.png">

**Comment by karenetheridge** [comment]
This is hard to reproduce without seeing what's in your database.

**Comment by karenetheridge** [comment]
Can you provide (in a gist, not this ticket please) the full json response you are seeing from that endpoint? that will help.

**Comment by karenetheridge** [comment]
these aren't dupes; will normalize the data so that's more clear.
